### ISSUE TITLE
Promote some (all?) docs 1.0 redirects from temporary to permanent

### ISSUE THREAD

**Issue by epbarger** [EnterpriseDB/docs#1020]
Our initial set of redirects from docs 1.0 to docs 2.0 will all be "temporary" redirects until we have confidence that the redirects are all correct. Once this is the case, we probably want to change some or all of these redirects to "permanent" redirects, as besides being more performant, my impression is this would be better for SEO.

There are three types of redirects in this set that I think we need to consider separately.

## Redirects from a versioned path to a new versioned path, not the latest version of the product

Example - PEM 8.0 (latest version is 8.0.1)

https://www.enterprisedb.com/edb-docs/p/edb-postgres-enterprise-manager/8.0 will redirect to https://www.enterprisedb.com/docs/pem/8.0/

I believe these redirects should become permanent, since once they are in place they shouldn't need to change.

## Redirects from a versioned path to a new versioned path, latest version of the product

Example - EPAS 13 (latest version)

https://www.enterprisedb.com/edb-docs/p/edb-postgres-advanced-server/13 will redirect to https://www.enterprisedb.com/docs/epas/13/

https://www.enterprisedb.com/docs/epas/13/ then temp redirects to https://www.enterprisedb.com/docs/epas/latest/

Should the legacy redirect be permanent or temporary? Our thinking is that the redirect should be permanent, but will Google be upset if a permanent redirect leads to temporary one? And when this version is no longer the latest version (IE when EPAS 14 is out), will we have SEO issues? Or will it work as expected, with the permanent redirect still going to `/docs/epas/13/ `, and that path no longer temp redirecting to `/docs/epas/latest/` once version 14 is out?

## Redirects from a latest path to a new latest path

Example EPAS 13 (latest version)

https://www.enterprisedb.com/edb-docs/p/edb-postgres-advanced-server/latest will redirect to https://www.enterprisedb.com/docs/epas/latest/

I believe there is no problem making these permanent, as if you're clicking a url with `latest` in it, you would expect to land on the latest version always. This does prevent us from easily changing these redirect, say if for instance the latest version removed the content on a page and put it on a different page, but this should be handled with internal redirects inside Docs 2.0.

**Comment by epbarger** [comment]
@josh-heyer FYI

**Comment by josh-heyer** [comment]
These should all be good. The only temp redirects should be /versioned/ -> /latest/

**Comment by epbarger** [comment]
Mark has made these redirect permanent, closing
