### ISSUE TITLE
Topics needed: Deployment Scripts Installation/Deployment

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#103]
## Summary:
        
Create an index.mdx file introducing this area at the location specified, identify topics needed to cover the material, and create new issues for them (unless such issues already exist, in which case note them in comments).
        
## Intended location:
        
postgresql_journey/02_installing/deployment-scripts

## Existing material:

Ansible scripts - what else is available?
https://www.enterprisedb.com/postgres-tutorials/how-deploy-ansible-scripts-edb-postgres-platform

**Comment by dougortiz** [comment]
We have two repositories:
- [Terraform Scripts](https://github.com/EnterpriseDB/postgres-deployment)
- [Ansible Scripts](https://github.com/EnterpriseDB/edb-ansible)
