### ISSUE TITLE
Feedback on /mysql_data_adapter/2.5.5/index.mdx

### ISSUE THREAD

**Issue by marclinster** [EnterpriseDB/docs#1039]
Why is the MySQL FDW called the 'MySQL Foreign Data Wrapper', but HDFS and Mongo are called 'Adapters'?

**Comment by abhilasha-narendra** [comment]
This issue has been fixed now, PFA the screenshot of the listing on the Docs site.
![image](https://user-images.githubusercontent.com/53602601/123377335-8c99a180-d5a9-11eb-96e8-7cb026740ca0.png)
