### ISSUE TITLE
Convert rstToMdx script to use Docker container

### ISSUE THREAD

**Issue by gsong** [EnterpriseDB/docs#1057]
We want to eliminate the need to install pandoc locally and rely instead on the Docker image with pandoc installed to do the work.

Convert `product_docs/convert.sh` to spin up a Docker container to do the work.

**Comment by gsong** [comment]
@cero-miedo @josh-heyer Can one of you point me to an example RST I can use for testing purposes?

**Comment by josh-heyer** [comment]
PEM docs are probably a good test case: https://github.com/EnterpriseDB/pem/tree/master/docs/en_US
