### ISSUE TITLE
Clarify Docker workflow

### ISSUE THREAD

**Issue by gsong** [EnterpriseDB/docs#1059]
<https://enterprisedb.atlassian.net/servicedesk/customer/portal/1/IT-36634>

* Private images should be hosted at Cloudsmith
* Ongoing discussion about public images

---

1. Does EDB have a Docker image namespace?
2. Where does EDB host its Docker images?

**Comment by josh-heyer** [comment]
FWIW, there's an EDB Quay repo: https://quay.io/organization/enterprisedb - used by the CNP stuff. Might wanna hit up the folks in #cloud-dev to see if this is part of a larger strategy.
