### ISSUE TITLE
Restore optional features during mdx to PDF conversion

### ISSUE THREAD

**Issue by gsong** [EnterpriseDB/docs#1060]
With https://github.com/EnterpriseDB/docs/pull/1047 we lost the ability to use the `--html` and `--open` flags with the tool.

Are both features still needed? If so, we'll need to restore the features.

**Comment by gsong** [comment]
@epbarger @cero-miedo @josh-heyer Want to weigh in with your opinions?

**Comment by epbarger** [comment]
I think it would be nice to keep them if possible.

`--open` is probably the more useful of the two for non-developers. Matt mentioned during standup that the docs team may be changing their processes to rely less on review PDFs, so I don't think it's a big deal to drop it. Maybe we could have have the `build-pdf` script output the pdf path to stdout as the last step, so you could pipe to `open` or something else? I think `open` is just on Mac IIRC.

`--html` is mostly just useful to help me debug the PDF script when changing styling etc. As long as it's still part of the actual script I don't care too much if it works in the docker env or not, but if it's simple to have it work in docker that would be a nice feature.

**Comment by josh-heyer** [comment]
Revisiting this: 

- we can / do / are building debugging functionality as-needed; don't think that (the `--html` flag or equiv) is needed when not actively developing the script. 
- docs team does not appear to have needed `--open` - perhaps @abhilasha-narendra can weigh in, but I think that was probably unnecessary.

**Comment by abhilasha-narendra** [comment]
We have not been using the --open flag, so I guess the doc team should be okay if we decide not to work on this flag.
