### ISSUE TITLE
Rename /kubernetes/cloud_native_operator/ to /kubernetes/cloud_native_postgresql/

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#1073]
[Per Adam Wright](https://edb.slack.com/archives/CU5QEU5L7/p1615919026001400):

> The Cloud Native PostgreSQL URL should be the product name to future proof against additional Operators being added with separate documentation, e.g., Cloud Native BDR, Cloud Native Barman.

**Comment by epbarger** [comment]
Addressed by https://github.com/EnterpriseDB/docs/pull/1107
