### ISSUE TITLE
Problem on https://www.enterprisedb.com/edb-docs/d/edb-postgres-replication-server/user-guides/user-guide/6.2/EDB_Postgres_Replication_Server_Users_Guide.1.61.html

### ISSUE THREAD

**Issue by mucharafal** [EnterpriseDB/docs#1223]
Point 8.4.33
Case of command is wrong - only accepted by cli format is fully lowercase (`confschedulemmr`), but in example there is mixed (`confscheduleMMR`), what could be confusing

**Comment by Rasika03** [comment]
Raised A Bug in JIRA:

https://enterprisedb.atlassian.net/browse/XDB-732. 

Hence closing the ticket.
