### ISSUE TITLE
PDFs are failing to build

### ISSUE THREAD

**Issue by cero-miedo** [EnterpriseDB/docs#1228]
[See failed github actions for more information](https://github.com/EnterpriseDB/docs/actions)

### Things I've tried
* running `npm run build-all-pdfs-ci` locally
* removing problematic sources, eg. `product_docs/docs/ark` - this just kicked the can down the road and caused previously OK docs to fail.

### Problems with current PDF CI workflow
* generation script doesn't care about `build-sources.json`
* PDFs end up in git and are versioned - this isn't optimal

**Comment by josh-heyer** [comment]
Looks like the direct culprit here is https://github.com/EnterpriseDB/docs/commit/a93e24e8e16b4370380e979197d3058873c7bc5c#diff-84218f3163feb5e7662375ef8e747c389878e6e252d2044a32f96c60092da004 - this commit deleted a LOT of images. 

Working on reverting this.

We should probably fix the PDF generator to not fail on missing images... After adding a check for missing images somewhere first!
