### ISSUE TITLE
Husky pre-commit doesn't work in a git GUI

### ISSUE THREAD

**Issue by robert-stringer** [EnterpriseDB/docs#1347]
Since adding this husky stuff, I've noticed I can't commit using GitHub Desktop or Sourcetree.

Is there some additional set up that needs to be done to support this apps? Should maybe be added to the README.

**Comment by gsong** [comment]
@robert-stringer Can you edit the description to describe what happens when you try to commit? If a screencast is easier, feel free to attach that.

**Comment by robert-stringer** [comment]
![image](https://user-images.githubusercontent.com/62722976/117331479-b29aa380-ae8e-11eb-8f96-0aaa0d622e22.png)

This is what I'm seeing when commiting via Sourcetree

**Comment by robert-stringer** [comment]
Investigating [this](https://typicode.github.io/husky/#/?id=command-not-found)

**Comment by gsong** [comment]
@robert-stringer Try this:
1. Quit the Sourcetree app
2. In Terminal, `cd` to the project directory
3. Use `stree` to launch Sourcetree and try to commit
