### ISSUE TITLE
Replication Server PDF not downloading

### ISSUE THREAD

**Issue by Rasika03** [EnterpriseDB/docs#1357]
Hi,

While trying to download Replication Server PDf from production the following error is being encountered:

<img width="670" alt="Screenshot 2021-05-11 at 2 09 20 PM" src="https://user-images.githubusercontent.com/70322985/117790259-ce26f500-b266-11eb-852f-640a587ed55e.png">

**Comment by robert-stringer** [comment]
I think this might be a security related issue with Chrome. Downloading the PDF as part of a regular download, I'm able to view it. Other browsers such as Firefox and Safari work as expected.

**Comment by abhilasha-narendra** [comment]
This issue seems to be due to low internet bandwidth and is faced mostly for large docset such as EPAS, PEM, or Replication Server. If you faced this issue once when your bandwidth is lower, try clearing your cache before trying to download the PDF again. This worked for me and Nidhi.

**Comment by josh-heyer** [comment]
Reproduced in Chrome by throttling to 3G (fast or slow) speeds. Once failed, cache is poisoned - will not retry except on hard refresh.

**Comment by drothery-edb** [comment]
This is a Chrome bug and we can't fix it.
