### ISSUE TITLE
Feedback on /jdbc_connector/42.2.12.3/05_using_the_advanced_server_jdbc_connector_with_java_applications/index.mdx

### ISSUE THREAD

**Issue by yeroc** [EnterpriseDB/docs#1363]
Listing 1.1:

The `Class.forName("...")` call is not required for any JDBC 4-Compliant drivers.  In JDBC 4+ drivers are loaded automatically via Java's service loader mechanism.  Since 42.2.12.3 only supports JDBC 4+ this should be removed from the sample code.

**Comment by yeroc** [comment]
/jdbc_connector/42.2.12.3/05_using_the_advanced_server_jdbc_connector_with_java_applications/01_loading_the_advanced_server_jdbc_connector.mdx needs updates to correct the information regarding `Class.forName()` as this is not how drivers are normally loaded under JDBC 4+.  This documentation is out of date.

**Comment by josh-heyer** [comment]
Thanks @yeroc - this is excellent feedback. This shows up in probably a couple dozen other places as well, so we'll take a pass on this section and update it!
