### ISSUE TITLE
Request for OpenShift operator manifest sample

### ISSUE THREAD

**Issue by jericson-edb** [EnterpriseDB/docs#1366]
## Summary
Would be nice to have the Openshift Deployment Configs available for download for Backup.

## Where did you see the problem?

It looks like the user wants to save a page such as [Operator configuration](https://www.enterprisedb.com/docs/kubernetes/cloud_native_postgresql/operator_conf/#available-options) for offline use.

## Expected behavior
Many pages on EDB Docs have a "Download PDF" link. But that's not available on [Cloud Native PostgreSQL documentation](https://www.enterprisedb.com/docs/kubernetes/cloud_native_postgresql/). 

## Additional notes
This issue originated as an anonymous user feedback comment. I'm not 100% I got the details right.

**Comment by jericson-edb** [comment]
Yeah. I misread the comment. 🤦‍♂️

**Comment by josh-heyer** [comment]
I think this need is sufficiently addressed by the examples now present in the OpenShift topic: https://www.enterprisedb.com/docs/postgres_for_kubernetes/latest/openshift/

If more / different examples are needed, please raise another issue with details on what you'd like to see!
