### ISSUE TITLE
Idea for more details about configuring OpenShift 

### ISSUE THREAD

**Issue by jericson-edb** [EnterpriseDB/docs#1367]
## Summary
Where is the openshift yaml file to deploy the backup container?

## Where would you like to see this added?

Cloud Native PostgreSQL supports OpenShift, but the documentation is a little thin. Ideally add more detail to help someone get started with it or link to external documentation that does.

## Rationale
We got this question from anonymous user feedback, so someone is looking to configure OpenShift and isn't getting the help they need.

**Comment by josh-heyer** [comment]
Is there a particular part of the documentation where you'd see this fitting / see it lacking?
