### ISSUE TITLE
Regarding /supported-open-source/postgresql/installer/index.mdx

### ISSUE THREAD

**Issue by maximjob974** [EnterpriseDB/docs#1399]
## Summary
when i installed Postgresql version13 and run pgadmin 4 v5 I see error The pgAdmin 4 server could not be contacted:

## Where did you see the problem?

after pgadmin cannot start I saw error:

```
Python Path: "C:\Program Files\pgAdmin 4\v5\python\python.exe"
Runtime Config File: "C:\Users\Maxim\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Program Files\pgAdmin 4\v5\web\config.py"
Webapp Path: "C:\Program Files\pgAdmin 4\v5\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\pgAdmin 4\v5\python\python.exe C:\Program Files\pgAdmin 4\v5\web\pgAdmin4.py"
Traceback (most recent call last):
  File "C:\Program Files\pgAdmin 4\v5\web\pgAdmin4.py", line 98, in <module>

    app = create_app()
  File "C:\Program Files\pgAdmin 4\v5\web\pgadmin\__init__.py", line 347, in create_app
    if not os.path.exists(SQLITE_PATH) or get_version() == -1:
  File "C:\Program Files\pgAdmin 4\v5\web\pgadmin\setup\db_version.py", line 19, in get_version
    return version.value
AttributeError: 'NoneType' object has no attribute 'value'
```

## Expected behavior
I would like to run PostgreSQL properly

## Screenshots
![image](https://user-images.githubusercontent.com/75717821/118931417-a6631b80-b94f-11eb-9832-1a5d3f463520.png)

## Browser / Platform
Windows 10

## Additional notes
Anything else you'd like to add that might help us to fix the problem

**Comment by josh-heyer** [comment]
Hey @maximjob974 - could you try the suggestions [here](https://stackoverflow.com/questions/67093175/instal-postgres-sql-in-windows-10) and let me know if one of them helps?

You might also want to check out the pgAdmin bug reports in their Redmine tracker, as noted here: https://stackoverflow.com/questions/67527280/get-fatal-error-server-could-not-be-contacted-when-running-pgadmin4-nonetype/67541446#67541446
