### ISSUE TITLE
Problem on docs/efm/latest/efm_user/07_using_efm_utility/#efm_cluster_status

### ISSUE THREAD

**Issue by jericson-edb** [EnterpriseDB/docs#1491]
From feedback survey:

> Your path /usr/edb/efm-42/bin is wrong; it should be /usr/edb/efm-4.2/bin

**Comment by drothery-edb** [comment]
Abhilasha, this is in your content, correct?

**Comment by abhilasha-narendra** [comment]
Yes, I pushed PR #1499 to fix this issue.

**Comment by abhilasha-narendra** [comment]
The content has been updated on the Docs site: https://www.enterprisedb.com/docs/efm/latest/efm_user/07_using_efm_utility/
