### ISSUE TITLE
Make icons private again?

### ISSUE THREAD

**Issue by frago12** [EnterpriseDB/docs#1534]
Icons used to be installed from a Git submodule of a private repo.

Recently, we got rid of that private repo and moved the icons into this repository, making the icons public as a consequence.

If we have to make the icons private again I can see 2 potential options:

1. Go back to the Git submodule approach with the difference that now the repository will be hosted by the EnterpriseDB Github Org. (I'll see this as a temporary step before we get to number 2)
2. Move the icons to an internal npm package. We briefly talked about this before, there's already some infrastructure that will facilitate this but it will require some code refactoring.

**Comment by josh-heyer** [comment]
Given I'm pretty sure I never actually checked anything into the icons repo, having it as a submodule was mostly just an annoyance; guessing this will continue to be true for most writers and editors as well.

The current setup is convenient. But if we HAVE to put these somewhere else, my preference is probably an NPM repo.

**Comment by gsong** [comment]
I think in the meantime, we should look up the license of the icons we're using for this repo, and post that license to the repo.

@matt-edb @robert-stringer Can you help with tracking down the license for these icons?

**Comment by matt-edb** [comment]
Yep, I got you:
https://icons8.com/vue-static/landings/pricing/icons8-license.pdf

Here's the relevant clause (bottom of page 4):
```Images and Licensed Materials may be used in any manner without restriction as to the number of copies, or personal or commercial usage provided such usage complies with provisions within this Agreement. ```

Does that work?

**Comment by frago12** [comment]
@josh-heyer @gsong here is an initial exploration of what would take to consume icons from an npm package #1539
