### ISSUE TITLE
Add a `Backup tools` section with BART, Barman and pgBackRest under the `EDB PRODUCTS & TOOLS` section

### ISSUE THREAD

**Issue by sebasmannem** [EnterpriseDB/docs#156]
Currently the sidebar of [the staging doc system](https://edb-docs-test.netlify.app/) shows documentation for both `Barman` and `pgBackRest` under the `2NDQUADRANT` section.
Example image:
![Screenshot 2020-12-04 at 15 41 43](https://user-images.githubusercontent.com/12484310/101190871-47d40a80-3659-11eb-8ab9-124f375afd72.png)
First of all, `pgBackRest` is no `2NDQUADRANT` tool. Furthermore, it would be better to have all backup tools summarised together under the `EDB PRODUCTS & TOOLS` section.
Therefore I would like to request to add a sub section under the `EDB PRODUCTS & TOOLS` section called `Backup tools`, and under this section add the documentation for `Barman`, `pgBackRest` and `Backup and Recovery Tool`.

**Comment by cero-miedo** [comment]
Thanks for the feedback, these are now grouped under `Backup & Recovery Tools`
