### ISSUE TITLE
Regarding /kubernetes/cloud_native_postgresql/interactive_demo.mdx

### ISSUE THREAD

**Issue by SippingTheKoolaid** [EnterpriseDB/docs#1564]
## Summary
When checking status of the cnp cluster during the interactive demo, the cnp option is not available for kubectl.

$kubectl cnp status cluster-example
Error: unknown command "cnp" for "kubectl"

Did you mean this?
        top
        cp

Run 'kubectl --help' for usage.

## Where did you see the problem?

Interactive Demo just prior to Testing Failover section
[](https://www.enterprisedb.com/docs/kubernetes/cloud_native_postgresql/interactive_demo/)

## Expected behavior

Newly created Cloud Native PostrgreSQL cluster status returned

## Screenshots

n/a

## Browser / Platform

Chrome

## Additional notes

Completion of the demo required installation of the Cloud Native PostgreSQL plugin before being able to run **kubectl cnp**.  It appears the instruction for installation of the Could Native PostgreSQL plugin and the output from that was included in the sample output from the get cluster command **kubectl get cluster cluster-example -o yaml**  

To avoid confusion, installation instructions should be moved from the output and placed in a separate run box.

**Comment by josh-heyer** [comment]
Thanks! Looks like I missed a newline updating the output. Fix will be up momentarily - appreciate your time and thorough report!
