### ISSUE TITLE
Add K8s Journey 

### ISSUE THREAD

**Issue by theadamwright** [EnterpriseDB/docs#157]
## Summary
Updating content sourced from edb-k8s-doc with the new EDB Cloud Native PostgreSQL. The journey will then be the source for the containers and k8s quickstart and edb-k8s-doc will go private and eventually be deleted. 

EDB Containers and EDB Cloud Native PostgreSQL 
- Docker
- K8s_CLI
- K8s-Helm
- K8s-Postgres-Operator
- K8s-BDR-Operator 

## Where would you like to see this added?

https://github.com/EnterpriseDB/docs/tree/develop/advocacy_docs/containers_k8s
 
##  Note
These quickstarts containing different way to deploy EDB containers are separate from the official documentation.

**Comment by cero-miedo** [comment]
Looping in @josh-heyer for further triage

**Comment by theadamwright** [comment]
This enhancement is no longer required.
