### ISSUE TITLE
Feedback on /epas/12/11_epas_guide/index.mdx

### ISSUE THREAD

**Issue by shannon7wallace** [EnterpriseDB/docs#161]
blank page

**Comment by cero-miedo** [comment]
Steps to rectify:

* `rm index.mdx`
* `mv 01_introduction.mdx index.mdx`
* Edit front matter on `index.mdx`

**Comment by cero-miedo** [comment]
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/62722976/102208981-0bf63c00-3ec8-11eb-99af-443d77b34271.png">
