### ISSUE TITLE
Additions to the head section of each doc

### ISSUE THREAD

**Issue by pankiledb** [EnterpriseDB/docs#163]
These tags need to be in the head of each new page. n 

1. `<title>` tag
1. meta description: use if available, DO NOT use the same damn description on every page!
1. meta keywords: TBD
1. meta property og: title
1. meta property og: description
1. canonical Url: let's make that a stage #2 rollout so that we can gauge the effect independently from that of the redirects that will necessarily happen as part of the migration

**Comment by epbarger** [comment]
1. Should be set
2. Currently no pages seem to have custom descriptions set, so it'll always fall back to the default one. I can change this to not have a description tag if there is not a custom description. Maybe we also want to generate these custom descriptions for each page automatically.
3. Let me know what this should be
4. Exists, is the same value as `<title>`
5. Exists, is the same value as meta description
6. I'll remove this for now, makes sense!

**Comment by epbarger** [comment]
Addressed with https://github.com/EnterpriseDB/docs/pull/166
