### ISSUE TITLE
Stop checking in PDFs

### ISSUE THREAD

**Issue by jericson-edb** [EnterpriseDB/docs#1632]
We are committing PDFs to Git, which is not recommended. Worse, it's making everything slower than it should be as we ship patches for binary files back and forth. The goal is to remove PDFs from Git history and [move other binary files (screenshots, etc.) to LFS](https://docs.github.com/en/github/managing-large-files/versioning-large-files/moving-a-file-in-your-repository-to-git-large-file-storage). Before we do that, however, we need to stop checking in PDFs and manually move them to Netlify/Heroku.

Here's the plan for that step. I'm going to:
1. create a new branch off of develop,
2. copy the .github/workflows/deploy-develop.yml action and edit it to only trigger when my new branch is pushed,
3. pull in the PDF generation step from .github/workflows/update-pdfs-on-develop.yml and
4. make sure this all works the way I think it does.

If that test works, we can retire the update-pdfs-on-develop workflow and fix the other workflows to do what we need. If it doesn't work, I can test on my branch without (I think) disrupting anyone else. (Also, it's close enough to the weekend that I don't think there are people around to be disrupted.)

**Comment by gsong** [comment]
@jericson-edb Sounds like a solid plan. Good luck.

**Comment by jericson-edb** [comment]
Ok, [this test](https://github.com/EnterpriseDB/docs/runs/3204818590?check_suite_focus=true) seems to have worked. But it occurs to me that the PDFs are still in the repo so I can't be sure it's picking up the generated PDFs. So I'm going to remove the PDFs from my branch (not history, just a `git rm`) and see what happens. Also, I'm not sure we need to install Python since the VM image includes it. Maybe we need a specific Python? Anyway, it doesn't hurt to test it.

**Comment by gsong** [comment]
Check out https://github.com/EnterpriseDB/docs/blob/develop/docker/images/Dockerfile.pdf-builder for specific Pandoc version. Ubuntu installs Python 3.8.1.

**Comment by jericson-edb** [comment]
Left the Python install alone. :-)

Removing the PDFs does seem to have worked out. Noticed there is a build timestamp to prove [the right version was delivered]()https://610469e3ed4e0b30106f1e45--edb-docs-staging.netlify.app/docs/static/3fc1582e1974e33ecdfc652f40fa0fac/epas_v13_documentation.pdf):

> Built at 2021-07-30T20:59:3

It looks like this is working! Gonna clean up my branch and do a PR next. (Not sure if it'll be today or Monday.)

**Comment by gsong** [comment]
👏 Good work!

**Comment by jericson-edb** [comment]
Fixed by: https://github.com/EnterpriseDB/docs/pull/1640

Onward!
