### ISSUE TITLE
Clean PDFs from Git history and move large files to LFS

### ISSUE THREAD

**Issue by jericson-edb** [EnterpriseDB/docs#1673]
See also: #1632.

Now that we are no longer checking in PDFs, it's time to clear out Git history. I'm using the [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/):

```
git clone --mirror git@github.com:EnterpriseDB/docs.git
java -jar ../bfg-1.14.0.jar --delete-files '*.pdf' docs.git
cd docs.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push
```

(I had to remove branch protection for `develop` and `main`. There were also a ton of warnings about PRs, which is explained in [this blog post](https://christoph.ruegg.name/blog/git-howto-mirror-a-github-repository-without-pull-refs.html).)

Next we need to move large files to LFS, but we need to break up the work to avoid a `fatal: pack exceeds maximum allowed size` error. The problem appears to be that [the pack size for pushes is limited](https://stackoverflow.com/questions/15125862/github-remote-push-pack-size-exceeded) and this change exceeded that limit. So we need to run the BFG process and push a separate time:

```
cd ..
java -jar ../bfg-1.14.0.jar --delete-files '*.{png,jpg,jpeg,1png,zip,ico}' docs.git
cd docs.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push
```

And then add the files to LFS:

```
git clone git@github.com:EnterpriseDB/docs.git
cd docs
git lfs track '*.jpg'
git commit -m 'Add JPG files to LFS' -a
git push
```

Repeat for each type of file we want to add.

**Comment by gsong** [comment]
Sounds like a perfect plan, good luck, Jon.

**Comment by gsong** [comment]
@jericson-edb Can this issue be closed? You can still reference it.

**Comment by jericson-edb** [comment]
Yep. It's done. 🎉
