### ISSUE TITLE
Move GitHub Actions to Docker

### ISSUE THREAD

**Issue by jericson-edb** [EnterpriseDB/docs#1696]
We'd like to use Docker for GitHub Actions. There are several reasons to do this, including testing our Docker image. To break up the task into sub tasks we need to:

1. Answer: Where do we host public Docker images?
2. Create a GitHub Action to build the Docker image when any file in the `docker` directory is changed.
3. Update GitHub Actions to build to Docker.

Not urgent, but this will simplify life for us in the future.

**Comment by josh-heyer** [comment]
Another good reason to do this: if we were automating the building of docker images we might be able to reduce issues experienced locally when build steps / dependencies change.
