### ISSUE TITLE
Banner on EDB Cloud pages

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#1697]
We want a banner on all the pages in the EDB Cloud preview doc in case they come up in search.

The proposed banner text is: 

EDB Cloud is currently in Preview mode. If you would like to sign up, see [EDB Cloud Preview Signup](page>https://resources.enterprisedb.com/postgres-database-as-a-service-dbaas-cloud-postgresql/).

See https://docs.google.com/document/d/12GWTtD6pguWGceYK1b0hIc3dYNe_-1jvIE91ACrRz7Y/edit# for background.

**Comment by drothery-edb** [comment]
@frago12 jfyi, this is higher priority than the #1620 one as it is a blocker for merging the edbcloud-beta branch. We need to do the merge so we can test out the link from the Cloud UI. Thanks.

**Comment by frago12** [comment]
@drothery-edb yeah, I'm working on it, I', going to have a PR in place today. FYI it'll require some updates to the frontmatter of each of the edbcloud pages.
