### ISSUE TITLE
Combining issues relating to /epas/12/01_epas_inst_linux/02_using_a_package_manager_to_install_advanced_server.mdx

### ISSUE THREAD

**Issue by sheet20** [EnterpriseDB/docs#172]
Installing Advanced Server on a Linux Host section is split into:

1. Installing Advanced Server on a CentOS Host
2. Installing Advanced Server on a RHEL Host
3. Installing Advanced Server on a CentOS/RHEL7 ppcle64le Host
with detailed installation steps for above platforms. The content needs to be replaced with the available content on https://www.enterprisedb.com/edb-docs/static/docs/epas/12/EDB_Postgres_Advanced_Server_Installation_Guide_Linux_v12.pdf
OR
https://www.enterprisedb.com/edb-docs/d/edb-postgres-advanced-server/installation-getting-started/installation-guide-for-linux/12/EDB_Postgres_Advanced_Server_Installation_Guide_Linux.1.06.html#pID0E0MU0HA

**Comment by cero-miedo** [comment]
@sheet20 Could you please link to the latest RST source for how this page should be displayed? It appears this content is vastly different from what you've linked. To fix this, I'd need to convert the RST for this entire section.

**Comment by sheet20** [comment]
Hi Robert,

The rst source for linux v12 guide is checked in to the edb-documents >
EPAS_13 branch under epas_inst_linux folder on Github.
In the pas_inst_linux folder, refer the
using_a_package_manager_to_install_advanced_server.rst page.

Let me know if you can pull the source? or else I'll mail you the rst file
for using_a_package_manager_to_install_advanced_server.rst page.

**Comment by sheet20** [comment]
Ignore my previous email...

For Linux v12 version, we have docx for Linux guide checked in under
edb-documents > EPAS_12 branch. RST format is supported for v13 only and
prior versions are in DOCX format.
Let me know whether you're able to pull the linux v12 docx.
