### ISSUE TITLE
Set up blanket redirect from Docs 1.0 to Docs 2.0

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#1803]
Part of the process of deprecating Docs 1.0 - so we can see if there are any issues before we have IT take the site down.

**Comment by gsong** [comment]
See https://github.com/EnterpriseDB/enterprisedb.com/issues/703. IT is ready to shut down `/edb-docs`.

**Comment by josh-heyer** [comment]
This should be done as part of IT-34110

**Comment by josh-heyer** [comment]
See #2248
