### ISSUE TITLE
Cleanup advocacy section

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#1834]
## Summary

The link to Format & Style is broken

## Where did you see the problem?

In the section titled 'Further reading'

## Expected behavior

The link would bring me to a page with information on format and style.

## Browser / Platform

Chrome

## Additional notes

Was this a test? :-)

**Comment by josh-heyer** [comment]
Left TODO: 
- Remove old Confluence side of things
- Communicate with Docs team / larger docs writer population within company
