### ISSUE TITLE
SQL guide /epas/13/epas_compat_sql/index.mdx misses `ALTER SYNONYM` 

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/docs#1840]
Hi, Support Team,

As far as I know, synonyms in EPAS contains `ALTER SYNONYM` command to change ownership of synonym object (c.f. legacy support portal Case#855382).

Can EDB team add this command usage to the documentation?

Best Regards.

**Comment by drothery-edb** [comment]
Created https://enterprisedb.atlassian.net/browse/DF-270 to track the change to the doc.

**Comment by drothery-edb** [comment]
Closed by https://github.com/EnterpriseDB/docs/pull/2675
