### ISSUE TITLE
Regarding /supported-open-source/postgresql/installer/03_using_stackbuilder.mdx

### ISSUE THREAD

**Issue by asjensse** [EnterpriseDB/docs#1853]
## Summary

List of extensions and modules found in each version of PostgreSQL Database

## Where would you like to see this added?

On the list of downloads

## Rationale

I need a specific extension (in my case Spatial Extensions). It's frustrating to install/uninstall different versions of PostgreSQL just to hope to find the extension in an older version

**Comment by drothery-edb** [comment]
We are providing this information for the extensions we support. See https://www.enterprisedb.com/docs/pg_extensions/. Do you have any suggestions for improvements?
