### ISSUE TITLE
Unexpanded `&rarr` which should be a right arrow on  /docs/bdr/latest/functions/

### ISSUE THREAD

**Issue by aaronfitzsimmons-edb** [EnterpriseDB/docs#1979]
From Álvaro on #edb-website slack channel.

"In this page, https://www.enterprisedb.com/docs/bdr/latest/functions/ there is a "synopsis" box for `wal_sender_stats`. There is an unexpanded `&rarr` there which should presumably be changed into an arrow pointing right."

**Comment by drothery-edb** [comment]
Fixed with https://github.com/EnterpriseDB/docs/pull/3417
