### ISSUE TITLE
Regarding /supported-open-source/postgresql/installer/04_installation_troubleshooting.mdx

### ISSUE THREAD

**Issue by nagimhmd** [EnterpriseDB/docs#1998]
## Summary

A short description of the problem you observed. Ex: "Code sample fails with error", "Link is broken"

## Where did you see the problem?

Describe the location within the text, ex: "in the section titled 'Further reading', the 2nd link doesn't load"

## Expected behavior

Describe what you expected, changes you'd like to see, etc.

## Screenshots

If applicable, paste / upload screenshots to illustrate the problem you saw

## Browser / Platform

Include the name of the browser and operating system you were using, along with versions

## Additional notes

Anything else you'd like to add that might help us to fix the problem

**Comment by nagimhmd** [comment]
502 ERROR
The request could not be satisfied.
CloudFront wasn't able to connect to the origin. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: M49UygknxmkHUOR8_5qFMU1921S99I9jJ6J3e59Uf9DmNdgZ2o_GVQ==

**Comment by drothery-edb** [comment]
Thank you for your feedback. IT has addressed this problem. We apologize for the inconvenience.
