### ISSUE TITLE
List of urls from old doc website

### ISSUE THREAD

**Issue by pankiledb** [EnterpriseDB/docs#200]
## Summary
I need the list of URLs from the old doc website

## Background info

The web team needs to generate metadata for each page for the new doc website. If we have the list of URLs from old doc website we can provide an excel with mapped meta data.

**Comment by josh-heyer** [comment]
Here is a list of URLs along with title, product and version (where we were able to extract those - may not be accurate in 100% of cases):
https://docs.google.com/spreadsheets/d/1vCcM6c2LL5p3DMc2OYyV9_kfRyZHmIoxYsHr5m-0chQ/edit?usp=sharing

Source data attached (zipped JSON)
[legacy_docs_scrape_dec_17.zip](https://github.com/EnterpriseDB/docs/files/5726367/legacy_docs_scrape_dec_17.zip)
