### ISSUE TITLE
Linking to old Platform Compatibility page on `/docs/efm/latest/efm_user/03_installing_efm/ `

### ISSUE THREAD

**Issue by aaronfitzsimmons-edb** [EnterpriseDB/docs#2009]
* Reported by Jimmy Angelakos in `#edb-website` *

[This EFM Docs page](https://www.enterprisedb.com/docs/efm/latest/efm_user/03_installing_efm/) contains a link to [the old product compatibility page](https://www.enterprisedb.com/services-support/edb-supported-products-and-platforms), which has now been replaced by a [new page](https://www.enterprisedb.com/product-compatibility) on the new EDB website.

The same problem occurs on [this PEM Docs page](https://www.enterprisedb.com/docs/pem/latest/pem_inst_guide_linux/02_pe:m_hardware_software_requirements/) which should also link to the [new product compatibility page](https://www.enterprisedb.com/product-compatibility)

It's likely that this will also need to be updated across other pages in the product library.

**Comment by drothery-edb** [comment]
Thanks for reporting the problem. I have a PR that is pending a review. We should have this fixed shortly.
