### ISSUE TITLE
Move EnterpriseDB/parameterize-docs-nunjucks into the docs repo

### ISSUE THREAD

**Issue by jaek-s** [EnterpriseDB/docs#2023]
The [EnterpriseDB/parameterize-docs-nunjucks](https://github.com/EnterpriseDB/parameterize-docs-nunjucks) repo is used to generate installation docs for various products. Since that code is directly related to docs, it should live in this repo.

- [ ] determine the best place for the script and template files to live
- [ ] determine the best place for rendered templates to be output
   - This could be left alone, and rendered templates can be output to a folder where they will then be moved into place
   - We can add some logic so that rendered templates are output directly where they should live in the docs project structure
- [ ] create an NPM script to make running the script easy

**Comment by drothery-edb** [comment]
I think we could do this in two steps: 

1. Move the repo to docs and keep the rendered files in an output file for now and manually move them into place
2. Later automate moving the rendered files to where they reside in the content.

It would be nice to do the first step as soon as possible.

**Comment by jericson-edb** [comment]
I believe we us [this process](https://stackoverflow.com/questions/17371150/moving-git-repository-content-to-another-repository-preserving-history/17373088#17373088) to move the repo here. From there we can adjust the render process to put files in the right location. Completing the automation can be done after we are confident the manual process is solid.
