### ISSUE TITLE
Feedback on /biganimal/release/reference/cli.mdx

### ISSUE THREAD

**Issue by VinnieGrack** [EnterpriseDB/docs#2038]
Hiya, I followed the instructions to download the biganimal latest cli `using` curl -LO "https://cli.biganimal.com/download/$(uname -s)/$(uname -m)/latest/biganimal" . It created a hidden folder. I changed the permission using chmod 755 on directory to run executables and added the cli path to default $PATH=~/biganimal. 

However, when i tried to run the cli command biganimal -h, ZSH through an error zsh: command not found: biganimal.
Could you help with step run on this on Mac using zsh?

thanks

**Comment by drothery-edb** [comment]
@zozowell , thanks for providing the command you used on MocOS using zsg: 
```
$ curl -LO "https://cli.biganimal.com/download/$(uname -s)/$(uname -m)/latest/biganimal"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.3M  100 13.3M    0     0   344k      0  0:00:39  0:00:39 --:--:--  363k
$ ls ./biganimal
./biganimal
```
```
$ chmod u+x ./biganimal
$ ./biganimal
The BIGANIMAL CLI.  This cli tool is capable of creating and managing database
cluster resources and events.  Before using this module, you must create
a credential using the 'biganimal create-credential' command.

Usage:
    biganimal [command]

Examples:
....
```

**Comment by VinnieGrack** [comment]
thanks, it's working now.  thanks
