### ISSUE TITLE
Regarding /supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx

### ISSUE THREAD

**Issue by aramosvizcarra** [EnterpriseDB/docs#2053]
## Summary

After unistalled Posgres in Mac all other programs installed with Stack Builder remain.

## Where did you see the problem?

There is no documentation how to uninstall extra programs installed with Stack Builder.
After unistalled Postgre using this instructions I still see Postgres products

/Library/P
Perl/                   PreferencePanes/        PrivilegedHelperTools/
**PgBouncer/**              Preferences/            Python/
**PostgreSQL/**             Printers/  

## Expected behavior

All Postgres products installed with Stack Builder should be also removed
## Browser / Platform

Mac

**Comment by drothery-edb** [comment]
Fixed by #3559
