### ISSUE TITLE
Add link checking as a build check / status check

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#2124]
We frequently do reorganization work on docs: renaming topics, moving sections around, altering section titles, etc. All of this work has the potential to break external and internal links - to avoid that outcome, it is helpful to add [redirects](https://github.com/EnterpriseDB/docs/blob/develop/docs/how-tos/avoid-breaking-links.md) and update internal links to reflect the new structure.

Right now, we depend on individuals identifying and mitigating these problems during their reorganization work. It would be beneficial to have an automated process that checks *at least* internal links to verify that they still work (go to an active page / existing section on the page), such that overlooked issues can be identified early (ideally: during a build or PR stage, failing that at least during a staging build). 

In the past, I've used https://github.com/filiph/linkcheck to check links in Docs. This tool is very fast and thorough, but requires a running site (and occasionally triggers HTTP 400 errors on Netlify for some reason). We might instead wish to find or devise a process that would perform these checks on static mdx files, or during a Gatsby build.

**Comment by gsong** [comment]
Another possible tool: https://www.npmjs.com/package/broken-link-checker

**Comment by josh-heyer** [comment]
Done as part of https://github.com/EnterpriseDB/docs/pull/5886
