### ISSUE TITLE
Feedback on /bdr/4.0/transaction-streaming.mdx

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/docs#2154]
In https://www.enterprisedb.com/docs/bdr/latest/transaction-streaming/#caveats

Some content of the `Note` stays outside of the block.
![image](https://user-images.githubusercontent.com/8018872/146665171-e985e337-aa7a-4435-8fff-88bb3e00257d.png)

Best Regards.

**Comment by josh-heyer** [comment]
Thanks! Got a PR out for this, will be corrected in a future build.
