### ISSUE TITLE
heading levels inconsistent in LiveCompare release notes

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#2159]
## Summary

The heading levels for the release notes change from level twos to level threes at the 1.9.1 release resulting in the later releases not showing up in the On This Page links.

## Where did you see the problem?

https://www.enterprisedb.com/docs/livecompare/latest/appendix_a/

[Appendix A: Release Notes](https://github.com/EnterpriseDB/LiveCompare/blob/master/docs/appendix_a.md)

## Expected behavior

All the releases should show up in the On This Page links.

## Screenshot
![liveCompare](https://user-images.githubusercontent.com/83650384/146980716-5bc2acf4-34ca-4164-a3db-322e998e3bc1.png)

**Comment by dougcalobrisi** [comment]
This should be resolved now, I believe.
