### ISSUE TITLE
Regarding /supported-open-source/postgresql/installer/04_installation_troubleshooting.mdx

### ISSUE THREAD

**Issue by rangexiesidili** [EnterpriseDB/docs#2177]
![image](https://user-images.githubusercontent.com/81523722/147800004-f924821d-2f92-4230-97dd-4affe8fc49ea.png)

**Comment by dwicinas** [comment]
Seems to be the same issue as https://github.com/EnterpriseDB/docs/issues/1449.

**Comment by drothery-edb** [comment]
Raised https://enterprisedb.atlassian.net/browse/DBP-191.
