### ISSUE TITLE
Clarify/correct example in Expose pgservices in Kubernetes doc

### ISSUE THREAD

**Issue by Harisai-edb** [EnterpriseDB/docs#2178]
## Summary

Code sample fails with error

## Where did you see the problem?

https://cloudnative-pg.io/documentation/current/expose_pg_services/#testing-on-minikube

in the section titled 'Testing on Minikube', the patch.yaml containing below.

spec:
  template:
    spec:
      containers:
      - name: nginx-ingress-controller
        ports:
         - containerPort: 5432
           hostPort: 5432

## Expected behavior

spec:
  template:
    spec:
      containers:
      - name: nginx-ingress-controller
        ports:
        image:   ??????????????????
         - containerPort: 5432
           hostPort: 5432

## Screenshots

[apple@localhost ~]$ kubectl patch deployment ingress-nginx-controller --patch "$(cat patch.yaml)" -n ingress-nginx
The Deployment "ingress-nginx-controller" is **invalid: spec.template.spec.containers[0].image: Required value**
[apple@localhost ~]$ 

## Browser / Platform

Include the name of the browser and operating system you were using, along with versions

[apple@localhost ~]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[apple@localhost ~]$ minikube version
minikube version: v1.24.0
commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b

[apple@localhost ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
[apple@localhost ~]$ 

CNP- operator version is 1.11.0

**Comment by Harisai-edb** [comment]
I am afraid the issue is still persistent with the latest version. 

```
[apple@localhost ~]$ kubectl patch deployment ingress-nginx-controller --patch "$(cat patch.yaml)" -n ingress-nginx
The Deployment "ingress-nginx-controller" is invalid: spec.template.spec.containers[0].image: Required value
[apple@localhost ~]$ cat patch.yaml 
spec:
  template:
    spec:
      containers:
      - name: nginx-ingress-controller
        ports:
         - containerPort: 5432
           hostPort: 5432
[apple@localhost ~]$ 
```

**Comment by Harisai-edb** [comment]
Sorry, I mistakenly closed this.

**Comment by djw-m** [comment]
Investigating:

So far, the suggestion that you add a controller value is bogus. The entire configuration is wrong here and the error message is just a red herring. 

These are the corrections I've worked out so far.

On Minikube you can setup the ingress controller running:

minikube addons enable ingress

Then, patch the tcp-service ConfigMap to redirect to the primary the connections on port 5432 of the Ingress:

~~kubectl patch configmap tcp-services -n kube-system \
  --patch '{"data":{"5432":"default/cluster-example-rw:5432"}}'~~

kubectl patch configmap tcp-services -n ingress-nginx \
  --patch '{"data":{"5432":"default/cluster-example-rw:5432"}}'


You can then patch the deployment to allow access on port 5432. Create a file called patch.yaml with the following content:

~~spec:
  template:
    spec:
      containers:
      - name: nginx-ingress-controller
        ports:
         - containerPort: 5432
           hostPort: 5432~~

```
spec:
  template:
    spec:
      containers:
        name: controller
        ports:
         - containerPort: 5432
           hostPort: 5432
```

~~and apply it to the nginx-ingress-controller deployment:~~

and apply it to the ingress-nginx-controller deployment:

~~kubectl patch deployment nginx-ingress-controller --patch "$(cat patch.yaml)" -n kube-system~~
```
kubectl patch deployment ingress-nginx-controller --patch "$(cat patch.yaml)" -n ingress-nginx
```

You can access the primary from your machine running:

psql -h $(minikube ip) -p 5432 -U postgres

Not mentioned - how to get the password for this user

```
kubectl get secret cluster-example-superuser -o jsonpath="{.data.password}" | base64 -d && echo
```

**Comment by djw-m** [comment]
Upstreamed fix in https://github.com/cloudnative-pg/cloudnative-pg/pull/2049 - awaiting outcome.

**Comment by djw-m** [comment]
Update - fix waiting on maintainer approval - has been ok'd to merge.

**Comment by josh-heyer** [comment]
Just need to import the fixes!
