### ISSUE TITLE
Missing EFM-1379 in EFM 4.2 release notes

### ISSUE THREAD

**Issue by tureba** [EnterpriseDB/docs#2205]
EFM 4.2 contained the change of [EFM-1379](https://enterprisedb.atlassian.net/browse/EFM-1379) as f284caf12ca953e1da4bc8cc4d5a3d2852034825, but that is not listed in the release notes and not in the [release announcement](https://enterprisedb.lightning.force.com/lightning/r/Technical_Alerts__c/a4V2J000001YxyoUAC/view) either.

Since that change has caused issues for customers that attempt to upgrade from an older EFM to/past 4.2, it should be documented where the customers can read so they will be prepared for the upgrade, instead of learning of it only when EFM refuses to start post upgrade.

**Comment by drothery-edb** [comment]
@tureba Would adding this row in the EFM 4.2 rel notes resolve this issue?

| Bug Fix | Failover Manager now creates a backup of the `pg_wal` directory contents even when a symbolic link is used for the `pg_wal` directory.

**Comment by tureba** [comment]
I think Jagdish's commit message might help us. For context, it is:

```
commit f284caf12ca953e1da4bc8cc4d5a3d2852034825
Author: Jagdish Kewat <jagdish.kewat@enterprisedb.com>
Date:   Thu Feb 11 19:07:01 2021 +0530
 
    EFM-1379 - Add validation to check if parent directory of pg_wal/pg_xlog is writable. If not then agent startup would fail. This would be for symlinks only. The actuallydirectory would be writable anyways, since it would be in data directory. Update clear WALs function to handle symlinks too. Oked by Vibhor, Bobby!
```

So I'd go with something like:

```
Add validation in the agent startup to check if the parent directory of pg_wal/pg_xlog is writable. This is necessary so EFM can later create a backup of that directory.
```

I think the backup feature is not new to that Jira ticket, so this is an extra validation to make sure that existing feature will work under more circumstances.

**Comment by ejones-edb** [comment]
This also occurred for customer Transactis in [RT77626](https://techsupport.enterprisedb.com/rt/ticket/77626/)

**Comment by drothery-edb** [comment]
Added this to the rel notes:
![image](https://user-images.githubusercontent.com/83650384/148832071-966a8d54-c2e7-447a-a2c9-7d33e0e3a33a.png)

Any comments or should I go ahead and merge the change?

See https://github.com/EnterpriseDB/docs/pull/2214

**Comment by ejones-edb** [comment]
Perhaps insert "If it is not not, an error is logged in the startup log and
the agent will not run." between the two sentences so that the potential
severity of the change is explicit.

**Comment by tureba** [comment]
@drothery-edb Oh, I don't think we should mention any ticket there. The change was not done because of 77626 at all (it's the other way around, that ticket would have benefited from the release notes mentioning the change).

The change proposed by @ejones-edb sounds ok, but maybe like:

```
Added validation in the agent startup to check if the parent directory of pg_wal/pg_xlog is writable. This is necessary so EFM can later create a backup of that directory. If that validation fails, an error is logged and the agent refuses to start.
```

**Comment by drothery-edb** [comment]
@tureba , @ejones-edb , how is this?

Added validation in the agent startup to check if the parent directory of pg_wal/pg_xlog is writable. The parent directory needs to be writable so EFM can later create a backup of it. If the new validation fails, an error is logged and the agent refuses to start

**Comment by tureba** [comment]
Looks good. Though I think the write permissions are necessary to restore the backup afterwards, so maybe:

Added validation in the agent startup to check if the parent directory of pg_wal/pg_xlog is writable. The parent directory needs to be writable so EFM can create a backup of it and later restore it. If the new validation fails, an error is logged and the agent refuses to start

**Comment by drothery-edb** [comment]
How is this?
![image](https://user-images.githubusercontent.com/83650384/149222104-29f914d0-6c20-46b4-bf0b-c6e1e0f03174.png)

**Comment by tureba** [comment]
That looks perfect! Very clear.
It's a big +1 from me.

**Comment by drothery-edb** [comment]
Great. Just merged the change and it will be in the next build. Thanks for your help.

**Comment by drothery-edb** [comment]
Change is live
