### ISSUE TITLE
Regarding /supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx

### ISSUE THREAD

**Issue by edbangma** [EnterpriseDB/docs#2224]
## Summary

'barman check pg' fails with PostgreSQL: FAILED

## Where did you see the problem?

After install and config of barman the check fails with 'barman check pg'
## Expected behavior

'barman check pg' should complete successfully

## Screenshots

![image](https://user-images.githubusercontent.com/97280765/149316977-e57d7b69-f376-4173-9add-cf80b4b9470a.png)

## Browser / Platform

I'm running the Interactive Demo step 2

## Additional notes

Seems it cannot reach the pg server/cluster?

**Comment by djw-m** [comment]
Issue is not repeatable if all steps are followed - tested with multiple runs.

If you miss running the creation of .pgpass you will get

```
Server pg:
        WAL archive: FAILED (please make sure WAL shipping is setup)
        PostgreSQL: FAILED
        directories: OK
        retention policy settings: OK
        backup maximum age: OK (no last_backup_maximum_age provided)
        backup minimum size: OK (0 B)
        wal maximum age: OK (no last_wal_maximum_age provided)
        wal size: OK (0 B)
        compression settings: OK
        failed backups: OK (there are 0 failed backups)
        minimum redundancy requirements: OK (have 0 backups, expected at least 0)
        pg_basebackup: OK
        pg_basebackup compatible: FAILED (PostgreSQL version: None, pg_basebackup version: 15.3)
        systemid coherence: OK (no system Id available)
        pg_receivexlog: OK
        pg_receivexlog compatible: FAILED (PostgreSQL version: None, pg_receivexlog version: 15.3)
        receive-wal running: OK
        archiver errors: OK
```

Which matches the original report, so I assume that step was missed.
