### ISSUE TITLE
Search Filter on EDB Doc Improvement

### ISSUE THREAD

**Issue by nataliawojcik27** [EnterpriseDB/docs#2243]
## Summary

Having the Search Filter on EDB Docs filter by product by default would be nice. 

## Where would you like to see this added?

Search Filter on EDB Docs

## Rationale

An example that occurred recently: when on the BigAnimal docs and looking for information about Azure Monitor as it relates to BigAnimal (by searching 'monitor') brings up docs in PEM or CNP instead of the BigAnimal pages that mention monitor.

**Comment by josh-heyer** [comment]
Related: https://github.com/EnterpriseDB/docs/issues/1874

**Comment by drothery-edb** [comment]
Kelly has had two additional customers bring this up. Can we up the priority on this?

**Comment by josh-heyer** [comment]
It's a trivial change, @drothery-edb - we can do it any time. The only question I'd have is: what should we do with advanced search? If you recall, #1892 changed that to "Search by Product", which makes not much sense in cases where the normal search is already doing that.

**Comment by drothery-edb** [comment]
Can we change it to Search all products? Basically flip the current experience?

**Comment by josh-heyer** [comment]
> Can we change it to Search all products? Basically flip the current experience?

Sure, seems reasonable.
