### ISSUE TITLE
Move docs 1.0 redirects to Netlify _redirects

### ISSUE THREAD

**Issue by gsong** [EnterpriseDB/docs#2248]
- [x] Test to make sure `/edb-docs` works on staging build in `docs` repo

  ```
  /edb-docs/test-123 /docs/whatever 301!
  ```

- [x] Test to make sure `/edb-docs` redirect works from [edb.com](https://github.com/EnterpriseDB/enterprisedb.com). Create a draft PR branch which points to preview Netlify instance:

  <https://github.com/EnterpriseDB/enterprisedb.com/pull/927>

  ```
  /edb-docs/* https://{netlify-subdomain}.netlify.app/edb-docs/:splat 200!
  ```

- [x] Append all redirects to `_redirects` file for Netlify deploy
- [x] Test to make sure `/edb-docs` redirect works from [edb.com](https://github.com/EnterpriseDB/enterprisedb.com). Create a **draft** PR branch which points to preview Netlify instance:

  ```
  /edb-docs/* https://{netlify-subdomain}.netlify.app/edb-docs/:splat 200!
  ```

- [x] Add a **real** PR to [edb.com](https://github.com/EnterpriseDB/enterprisedb.com):

  ```
  /edb-docs/* https://edb-docs.netlify.app/edb-docs/:splat 200!
  ```

- [x] Remove all nginx redirect artifacts
- [x] Test production redirects at docs production app
- [x] Switch edb.com to redirect to docs production app
- [x] Inform IT to remove docs 1.0 infrastructure

**Comment by josh-heyer** [comment]
Test #1 passed, @gsong - wanna set up #2? Host should be 61ef11d4a38872088206822f--edb-docs-staging.netlify.app

**Comment by gsong** [comment]
> Test #1 passed, @gsong - wanna set up #2? Host should be 61ef11d4a38872088206822f--edb-docs-staging.netlify.app

@josh-heyer See <https://github.com/EnterpriseDB/enterprisedb.com/pull/927>. The preview URL will be posted in the PR once the build is finished.

**Comment by gsong** [comment]
@josh-heyer I've modified <https://github.com/EnterpriseDB/enterprisedb.com/pull/927> to point to production docs Netlify instance. Once we've confirmed that the redirect works all the way when deployed to docs production, we can merge that PR at edb.com as well.

**Comment by josh-heyer** [comment]
With @jericson and @drothery-edb 's help, I believe we've identified the last of the issues with these redirects; all /edb-docs paths should resolve cleanly on the docs side of things now.
