### ISSUE TITLE
404 error - URL needs a redirect

### ISSUE THREAD

**Issue by timdaileyedb** [EnterpriseDB/docs#2251]
Google is still displaying this URL in search results: https://www.enterprisedb.com/docs/efm/latest/efm_user/15_configuring_ssl_authentication/

The correct link is: https://www.enterprisedb.com/docs/efm/latest/15_configuring_ssl_authentication/

The bad link is shown in this query: https://www.google.com/search?q=EDB+EFM+jdbc.sslmode%3D&oq=edb+efm&aqs=chrome.0.69i59j69i57j0i512l3j69i61j69i60l2.2200j0j4&sourceid=chrome&ie=UTF-8

**Comment by drothery-edb** [comment]
@josh-heyer, the topic already has this redirect in place:
redirects:
 - efm_user/15_configuring_ssl_authentication/
 
 What should it be?

**Comment by josh-heyer** [comment]
Should've been ../efm_user/15_configuring_ssl_authentication/ - see #2252 @drothery-edb

**Comment by josh-heyer** [comment]
Fixed by #2253
