### ISSUE TITLE
Search issues with EFM 

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#2369]
## Summary

Search results are not redirected to the correct URL

Details are here: https://enterprisedb.atlassian.net/browse/DF-286

**Comment by josh-heyer** [comment]
Appears to be the same as issue #1889 - note that the ACTUAL correct link is https://www.enterprisedb.com/docs/efm/latest/05_using_efm/#rhelcentos-7x-or-rhelrocky-linuxalmalinux-8x (no periods or slashes in that fragment)
