### ISSUE TITLE
Redirects: create a tool that checks for renamed files and changed paths and determines what redirect should be added

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#2380]
## Summary

To minimize the chance of broken links, it would be helpful to have a script that gives the writer a list of previously published files that have been renamed in a commit and suggest what the redirects should be.

This would provide the writer with guidance for adding redirects.

**Comment by josh-heyer** [comment]
I think a tool to check both path changes AND existing redirects to verify that there is coverage is appropriate here - IOW, should aim to eliminate both missed and unnecessary redirects.

**Comment by josh-heyer** [comment]
...A PR check to look for missed renames (delete + re-add in subsequent commit) would also come in handy here
