### ISSUE TITLE
Feedback on /epas/14/epas_compat_sql/36_create_table.mdx (missing keyword)

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/docs#2417]
Hi, Team,

The last line of `UNLOGGED` parameter misses a keyword compared with [the corresponding PGSQL doc page](https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-UNLOGGED).

> The unlogged table is automatically truncated after a crash or _unclean_ shutdown.

Best Regards.

**Comment by nidhibhammar** [comment]
Changes are done in PR: https://github.com/EnterpriseDB/docs/pull/2430
