### ISSUE TITLE
Feedback on /migration_portal/3.5.2/04_mp_migrating_database/03_mp_schema_migration.mdx

### ISSUE THREAD

**Issue by tureba** [EnterpriseDB/docs#2467]
In the instructions of ["Migrating to an existing on-premises EDB Postgres Advanced Server host"](https://www.enterprisedb.com/docs/migration_portal/latest/04_mp_migrating_database/03_mp_schema_migration/#migrate-schemas-on-linux), the example commands show `psql` metacommands starting with `\\` instead of `\`, which would be the correct prefix.

**Comment by drothery-edb** [comment]
Thanks for the feedback @tureba.
