### ISSUE TITLE
Regarding /supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx

### ISSUE THREAD

**Issue by changraekang** [EnterpriseDB/docs#2484]
## Summary

Uninstaller.app does not exsited 
## Where did you see the problem?

Describe the location within the text, ex: "in the section titled 'Further reading', the 2nd link doesn't load"

## Expected behavior

Describe what you expected, changes you'd like to see, etc.

## Screenshots

If applicable, paste / upload screenshots to illustrate the problem you saw

## Browser / Platform

Include the name of the browser and operating system you were using, along with versions

## Additional notes

Anything else you'd like to add that might help us to fix the problem

**Comment by drothery-edb** [comment]
We are checking into this with the Configuration Management team lead.

**Comment by drothery-edb** [comment]
Which PostgreSQL version and MacOS version are you using?

**Comment by drothery-edb** [comment]
If you didn't install Postgres with our installer, you won't have the uninstall app. 

We will add a note in our docs with a link to other popular MacOS installers.
