### ISSUE TITLE
Regarding /supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx

### ISSUE THREAD

**Issue by mistryvipul2002** [EnterpriseDB/docs#2543]
## Summary
uninstall-postgresql.app doesn't open up. Can't uninstall the postgres now.

**Comment by drothery-edb** [comment]
We are checking into this.

**Comment by mistryvipul2002** [comment]
PostgreSQL 14.3 / PostGIS 3.2.1/ Postgres.app v2.5.7

**Comment by josh-heyer** [comment]
@mistryvipul2002 - Postgres.app is different from the distribution shipped by EDB, and our uninstaller won't work to remove it. You can find the instructions for uninstalling Poostgres.app on their website: https://postgresapp.com/documentation/install.html
