### ISSUE TITLE
Regarding /kubernetes/cloud_native_postgresql/postgresql_conf.mdx

### ISSUE THREAD

**Issue by abip-sjarbini** [EnterpriseDB/docs#2576]
## Summary

LDAP Configuration Sample Definition has wrong stanza defined

## Where did you see the problem?

LDAP Configuration Section. spec.postgresql.parameters.ldap was given

## Expected behavior

by reading the clusters.postgresql.k8s.enterprisedb.io CRD, it should be spec.postgresql.ldap instead

## Screenshots

![image](https://user-images.githubusercontent.com/102211786/164816216-2762bee8-26dd-4dee-bdd5-51c78927181b.png)

## Browser / Platform

NA

## Additional notes

NA

**Comment by josh-heyer** [comment]
Heh... A lot has changed in the 7 months this has languished - gonna queue it up for review in the next cycle.

**Comment by josh-heyer** [comment]
Still an issue - but should properly be fixed upstream: https://github.com/cloudnative-pg/cloudnative-pg/pull/1142
