### ISSUE TITLE
Nested ordered list should use alpa characters

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#2612]
## Summary

If we have a nested list, the automatic ordering should be:

1. First level
   a. Second level

Here is an example of how the formatting looks now: 
https://www.enterprisedb.com/docs/biganimal/latest/getting_started/creating_a_cluster/#cluster-settings-tab

Here is the source file:
https://github.com/EnterpriseDB/docs/blob/develop/product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx

**Comment by gsong** [comment]
This can definitely be styled via CSS:

```css
ol ol { list-style: lower-alpha; }
```

[See example](https://codesandbox.io/s/ol-styling-e5uu9c?file=/index.html).

**Comment by drothery-edb** [comment]
That's great. Could one of you help us implement it?

**Comment by gsong** [comment]
@EnterpriseDB/x-advocates _ping_.
