### ISSUE TITLE
URL design

### ISSUE THREAD

**Issue by gsong** [EnterpriseDB/docs#2615]

**Comment by drothery-edb** [comment]
@josh-heyer how are these as possible options?

### Verbose option

`<product>/latest/installing/linux_<arch>/<product>_<os>_<os_version>_<arch>`

where `<os>` and `<os_version>` combinations are:
- rhel_8
- other_linux_8
- centos_7
- rhel_7
- sles_15	
- sles_12
- ubuntu_22
- ubuntu_20
- ubuntu_18
- deb_11
- deb_10

where `<arch>` is:
- x86_amd64 or a shortened version: x86
- power_ppc64le or a shortened version: power or ppc64le

Example: postgis/latest/installing/linux_x86_amd64/postgis_rhel_8_x86

### Terse option

`<product>/latest/installing/linux_<arch>/<product>_<os>_<os_version>`

where we are using a shortened version of `<arch>`and not including `<arch>` in the topic file name.

Example: postgis/latest/installing/linux_x86/postgis_rhel_8

**Comment by drothery-edb** [comment]
Refinements from 9/9 meeting:
arch for Linux should be either x86_64 or ppc64le to match what is in the product registry

We might want to repeat the arch info in the topic file names

Linux OS names are tbd

**Comment by drothery-edb** [comment]
https://github.com/EnterpriseDB/docs/pull/3256
