### ISSUE TITLE
Feedback on /epas/14/epas_compat_cat_views/41_dba_jobs.mdx

### ISSUE THREAD

**Issue by ManfredDrozd** [EnterpriseDB/docs#2624]
I have installed EDB Postgres Advanced Server 14.2 on Windows for porting an Oracle application to EDB Postgres.

The package DBMS_JOB is available but I'm missing the views ALL_JOBS, DBA_JOBS, USER_JOBS.

**Comment by nidhibhammar** [comment]
@ManfredDrozd, you can see https://www.enterprisedb.com/docs/epas/latest/epas_compat_bip_guide/03_built-in_packages/05_dbms_job/ and make sure that the pgAgent service is started.
