### ISSUE TITLE
Feedback on /edb_plus/40/04_using_edb_plus.mdx

### ISSUE THREAD

**Issue by ManfredDrozd** [EnterpriseDB/docs#2625]
When starting EDB*Plus you can specify a script name. 

Unfortunately this script is executed BEFORE the connect to the database. This is different to Oracle behavior. Oracle scripts, e.g. login.sql are executed AFTER connection to the database.

**Comment by drothery-edb** [comment]
@ManfredDrozd Thank you for your feedback. The associated Jira ticket for updating the content is: https://enterprisedb.atlassian.net/browse/DF-295.

**Comment by drothery-edb** [comment]
What the team found through testing was EDB*Plus first connected to the database before executing the script.  We believe what caused the confusion was displaying the version number and copyright information after the script executes.  The version and copyright information should probably be displayed prior to connecting to the database and executing the script. The team will be creating a ticket to create this behavior.
