### ISSUE TITLE
Replication Server: clarify what permissions required to run the TRUNCATE command

### ISSUE THREAD

**Issue by mlewandowski-edb** [EnterpriseDB/docs#2702]
The following paragraph in the "Postgres Subscription Database" section (https://www.enterprisedb.com/docs/eprs/latest/05_smr_operation/01_prerequisites/05_preparing_sub_database/#postgres-subscription-database) is either confusing or incorrect:

> The subscription database user must also be able to run the TRUNCATE command on the subscription tables. This requires the following:
> 
> Superuser privileges.
The ability to modify the system catalog tables to disable foreign key constraints on subscription tables. See [Disabling foreign key constraints for snapshot replications](https://www.enterprisedb.com/docs/eprs/latest/10_appendix/04_miscellaneous_xdb_processing_topics/04_disable_foreign_key_constraints_for_snapshot_replication/#disable_foreign_key_constraints_for_snapshot_replication) for more information on this requirement.

When I read that it makes it seem as if the SUPERUSER privilege is required to run the TRUNCATE command.  If that is actually what this paragraph is meant to convey, then I think it is wrong.  I believe the user would simply need to have been granted the TRUNCATE privilege on the tables that need to be truncated.  However if it is meant to convey that the SUPERUSER privilege is required for other aspects, such as disabling foreign key constraints, then the text should be updated to separate the need for the SUPERUSER privilege from the need to be able to TRUNCATE subscription tables.

**Comment by mlewandowski-edb** [comment]
@drothery-edb It probably is a good idea to get some clarity on what that content is meant to convey.  @zahid75 can you or someone on your team review?

**Comment by drothery-edb** [comment]
@mlewandowski-edb , I suggest you create a ticket for this instead of an issue. We don't seem to be getting traction on it. Can you create a ticket and link it to the issue?

**Comment by drothery-edb** [comment]
Pinged Zahid about this on Slack.

**Comment by mlewandowski-edb** [comment]
I created [XDB-1753](https://enterprisedb.atlassian.net/browse/XDB-1753) to track this issue in Jira and assigned it to the 7.4 release.

**Comment by drothery-edb** [comment]
Matt is checking with Zahid about this
