### ISSUE TITLE
Problem with creating a new cluster on Openshift 4.10

### ISSUE THREAD

**Issue by marekk1717** [EnterpriseDB/docs#2933]
I'm trying to setup a Postgresql cluster using EDB operator 1.15.1 but there is a problem with permissions during initdb phase. 
How can I solve this problem?

{"level":"info","ts":1657805159.141206,"msg":"Creating new data directory","logging_pod":"posgresql-cluster1-1","pgdata":"/var/lib/postgresql/data/pgdata","initDbOptions":["--username","postgres","-D","/var/lib/postgresql/data/pgdata","--encoding=UTF8","--lc-collate=C","--lc-ctype=C"]}
{"level":"info","ts":1657805159.1589084,"logger":"initdb","msg":"The files belonging to this database system will be owned by user \"postgres\".\nThis user must also own the server process.\n\nThe database cluster will be initialized with locale \"C\".\nThe default text search configuration will be set to \"english\".\n\nData page checksums are disabled.\n\ncreating directory /var/lib/postgresql/data/pgdata ... ","pipe":"stdout","logging_pod":"posgresql-cluster1-1"}
**{"level":"info","ts":1657805159.1589735,"logger":"initdb","msg":"initdb: error: could not create directory \"/var/lib/postgresql/data/pgdata\": Permission denied**\n","pipe":"stderr","logging_pod":"posgresql-cluster1-1"}
{"level":"error","ts":1657805159.1590111,"msg":"Error while bootstrapping data directory","logging_pod":"posgresql-cluster1-1","error":"error while creating the PostgreSQL instance: exit status 1","stacktrace":"github.com/EnterpriseDB/cloud-native-postgres/pkg/management/log.Error\n\tpkg/management/log/log.go:165\ngithub.com/EnterpriseDB/cloud-native-postgres/internal/cmd/manager/instance/initdb.initSubCommand\n\tinternal/cmd/manager/instance/initdb/cmd.go:137\ngithub.com/EnterpriseDB/cloud-native-postgres/internal/cmd/manager/instance/initdb.NewCmd.func1\n\tinternal/cmd/manager/instance/initdb/cmd.go:99\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\tcmd/manager/main.go:61\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/proc.go:2...
Error: error while creating the PostgreSQL instance: exit status 1

**Comment by josh-heyer** [comment]
Hi @marekk1717,

For questions such as this, you're best off contacting our support team - you can find our support center at: https://www.enterprisedb.com/services/support

For reference on setting up the EDB Postgres for Kubernetes operator on OpenShift, see: https://www.enterprisedb.com/docs/postgres_for_kubernetes/latest/openshift/
