### ISSUE TITLE
Regarding /supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/01_invoking_the_graphical_installer.mdx

### ISSUE THREAD

**Issue by Edu-Beltz** [EnterpriseDB/docs#2942]
After right-click on the installer icon and select Run as Administrator, I've got next message
Error
              There has been an error.
              Unable to write inside TEMP environment variable path.
             
Please could you give me a way to fix the problem and install it on my win 10?

**Comment by drothery-edb** [comment]
Thanks for the feedback. We are checking into this and will get back to you.

**Comment by drothery-edb** [comment]
From Sandeep: 
>seems to be because the %TEMP% (the default system temp) is not writable. This location is where the installer would create the temporary files for installation.  The system temp is usually world writable so I’m not sure why that error. I believe it was already documented on how to specify the non-default temporary location if there is a need. If not, I can find tomorrow and get back with that information
