### ISSUE TITLE
Page titles should always include the product name

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#2978]
## Summary

Right now, all page titles include a boilerplate "EDB Docs" prefix, but do not include the product name unless added manually by an author.

## Problem

Examples:

1. https://www.enterprisedb.com/docs/biganimal/latest/using_cluster/05_monitoring_and_logging/ - title is "EDB Docs - Monitoring and logging" (no mention of BigAnimal)
2. https://www.enterprisedb.com/docs/biganimal/latest/using_cluster/05_monitoring_and_logging/monitoring_from_azure/ - title is "EDB Docs - Viewing metrics and logs from Azure" (no mention of BigAnimal)
3. https://www.enterprisedb.com/docs/biganimal/latest/ - title is "EDB Docs - BigAnimal" (author included the product name)
4. https://www.enterprisedb.com/docs/biganimal/latest/free_trial/ - title is "EDB Docs - Getting started with the BigAnimal free trial" (author included the product name)

In examples #1 and #2, it would benefit both searchers (who may not be able to easily identify the context of the result from the title + excerpt) and our SEO (increasing the ranking and specificity of product names / trademarks) to mechanically add the product name as a prefix, e.g. "EDB Docs - BigAnimal - Monitoring and logging"

In examples #3 and #4, the context is evident from the existing title.

## Recommendation

Mechanically add the product name as a secondary prefix (after "EDB Docs") to titles that do not already contain the product name.

**Comment by josh-heyer** [comment]
After some discussion with @djw-m , we have the following idea:

1. Trim `EDB ` from the start of the product name
1. Take title and prefix with `EDB <product name> Docs - `
1. Don't worry about product name being integral to the title - repetition is fine

**Comment by gvasquezvargas** [comment]
Outdated.
