### ISSUE TITLE
Feedback on /biganimal/release/free_trial/detail/create_a_cluster/create_cluster_cli.mdx

### ISSUE THREAD

**Issue by VinnieGrack** [EnterpriseDB/docs#3055]
Hiya,

This is interesting that we mentioned on how to modify the directly permission on BigAnimal CLI post installed. However, Next command which seems to suggest that you autocomplete enabled bcoz now you switched into biganimal, instead of /path/to/biganimal. I felt that is confusing. Could you add further instructions to explain to how to enable autocomplete?

> _Linux and MacOS note
> If you're on a Linux or MacOS system, you'll need to mark the biganimal file as executable by running 
_```
chmod +x [/path/to/biganimal] before you can use it._

biganimal create-credential -a portal.biganimal.com -o 443 -n newuser
```_


**Instructions should be something like to make it seems to autocomplete to biganimal**
-----------------------
chmod +x [/path/to/biganimal]
Copy the binary to a folder in your PATH. If you have already installed a version of BigAnimal, then we recommend creating a $HOME/bin/biganimal and ensuring that $HOME/bin comes first in your $PATH

mkdir -p $HOME/bin && cp ./biganimal $HOME/bin/biganimal && export PATH=$HOME/bin:$PATH

(Optional) Add the $HOME/bin path to your shell initialization file so that it is configured when you open a shell

echo 'export PATH=$PATH:$HOME/bin' >> ~/.bash_profile

After you install biganimal, you can verify its version with the following command:

biganimal version --short --client

**Comment by josh-heyer** [comment]
Good call. I've trimmed your suggestion down a bit, as modifying shell init files isn't necessary for the rest of the examples on the page (and kinda opens up a can of worms when dealing with multiple shells - e.g. zsh users should probably be modifying .zenv). Changes in #3484
