### ISSUE TITLE
Navigation to main landing page for a product or doc is dropped after navigating to a child topic (advocacy_docs template)

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#3273]
This issue is showing up with content we are developing under the pg_extensions "product" using the advocacy_docs template.

When you navigate to one of the extension topics in the hierarchy, you can no longer navigate back to the main extensions landing page without using the back arrow on your browser.

Steps to recreate: 

1. Go to https://deploy-preview-3245--edb-docs-staging.netlify.app/docs/pg_extensions/.
2. Select LDAP sync.
    The link to the Extensions landing page is replaced by the link to the LDAP sync landing page.
![image](https://user-images.githubusercontent.com/83650384/196966400-a98d5738-bcbd-4abf-9cf4-2927d3d246f9.png)

**Comment by josh-heyer** [comment]
Needs to be completed before end of November
