### ISSUE TITLE
Feedback on /pem/8/considerations/pem_pgbouncer/configuring_pgBouncer.mdx

### ISSUE THREAD

**Issue by ashersilver** [EnterpriseDB/docs#3329]
These are **terrible** instructions: Im having to hack my way through them.
pgbouncer on RHEL 8 installs config files to /etc/pgbouncer (not /etc/edb/pgbouncer1.9)

Its not clear how to set up the user list.txt file (login, run the query as NOT superuser, logout?)

The references in the pgbouncer.ini file don't correspond to the options in the documentation (where do we find auth_user?)

We don't create permissions to read the pid files, the ca, key cert files, create the log and pid files etc. (maybe I am wrong here).

the database connection strings used in the pgbouncer.ini copy as follows:
`
pem = port=5444 host=/tmp dbname=pem auth_user=pgbouncer
pool_size=80 pool_mode=transaction

\* = port=5444 host=/tmp dbname=pem auth_user=pgbouncer
pool_size=10
`
host = /tmp doesn't seem to make sense (localhost, 127.0.0.1 maybe?)
can we split the database options onto 2 lines?

the data directory of the pem may not be what is used in the example, unless this example follows from another example?

**Comment by josh-heyer** [comment]
Thanks @ashersilver - this is useful feedback, definitely some corrections and improvements to be made on this topic. We'll review & prioritize these corrections in our upcoming cycle!

**Comment by drothery-edb** [comment]
Fixed by https://github.com/EnterpriseDB/docs/pull/3513
