### ISSUE TITLE
Problem on https://www.enterprisedb.com/docs/biganimal/latest/ BigAnimal Page

### ISSUE THREAD

**Issue by theoj178** [EnterpriseDB/docs#3362]
BigAnimal should be called "EDB BigAnimal" in all instances on the page.
https://www.enterprisedb.com/docs/biganimal/latest/

**Comment by drothery-edb** [comment]
Being addressed with https://github.com/EnterpriseDB/docs/pull/3374

**Comment by drothery-edb** [comment]
Changes are now live.
