### ISSUE TITLE
PGD: PgBouncer is no longer used by HARP

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#3439]
## Summary

The PGD docs state that PgBouncer is a requirement for HARP and that it uses its binaries, which is no longer the case.
- https://www.enterprisedb.com/docs/pgd/latest/harp/03_installation/
- https://www.enterprisedb.com/docs/pgd/latest/harp/04_configuration/

This issue was brought to our attention by Jimmy Angelakos in this Slack message: https://edb.slack.com/archives/CU5QEU5L7/p1670856437510169

**Comment by drothery-edb** [comment]
@mwanner @PJMODOS we received this feedback on the PGD 4 docs through Slack. Can you assign someone on your team to update the doc to reflect the changes in v4 regarding PgBouncer and HARP? I thought it would be straightforward and something I could do, but it requires an SME. 

cc: @kelpoole

**Comment by ashutosh-bapat** [comment]
@drothery-edb I am not aware of this change, but it seems an old change (this issue shows 12 Dec.) Can you please create a JIRA in BDR project to track this? Please specify deadline, if any. I don't know how much work is involved here; might be simpler or might be not. But the team is involved in PGD 5.0 right now and does not have bandwidth to take this up immediately. We will prioritise it among other things. Or the other option is to  check with Bryan, if he can take care of this.

**Comment by drothery-edb** [comment]
@bryan-bar is this something you can take care of either by identifying the specific doc changes needed or by making the changes yourself?

**Comment by ashutosh-bapat** [comment]
@drothery-edb, I think you want to ask @dbgreen
