### ISSUE TITLE
Regarding /supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/01_invoking_the_graphical_installer.mdx

### ISSUE THREAD

**Issue by Priyanshu-agr** [EnterpriseDB/docs#3460]
## Summary

Missing 'Port' figure on installation page.

## Where would you like to see this added?
![Screenshot 2022-12-17 215423](https://user-images.githubusercontent.com/98334616/208251614-434a91cc-7ce0-4246-bc61-07cd9bc42ef3.png)

A figure can be added between figure 5 and figure 6 where it shows the port dialog as it is missing.

## Rationale

For someone who is only going by seeing the images would panic that I got an extra wizard window.

**Comment by drothery-edb** [comment]
Fixed by #3490
