### ISSUE TITLE
Automate generation of installer landing pages 

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#3501]
Two types of landing / index pages need to be generated for most products:

1. Root "installing" landing page provides full index of all platform-specific instructions across OS and arch as well as links to subset landing pages for each OS/arch combo
2. OS/arch specific landing pages provide subset of index for topics in each section

See also: 
- https://github.com/EnterpriseDB/docs/pull/2834
- https://github.com/EnterpriseDB/docs/pull/3243

**Comment by drothery-edb** [comment]
Need this for #3502 by end of March for Ubuntu 22.04 releases
