### ISSUE TITLE
Problem on https://www.enterprisedb.com/docs/pgd/latest/harp/04_configuration/

### ISSUE THREAD

**Issue by nick-ivanov-edb** [EnterpriseDB/docs#3521]
## Summary

The HARP Proxy configuration section, specifically the description of the `type` setting, is outdated. The default is no longer `pgbouncer`, and the caution about using the "experimental" built-in proxy only in simplest scenarios seems wrong now. A customer complained the statement was confusing.

https://github.com/EnterpriseDB/docs/blob/develop/product_docs/docs/pgd/4/harp/04_configuration.mdx#harp-proxy-specific

## Where did you see the problem?

"HARP Proxy specific" section, bullet "type".

## Expected behavior

Need to confirm with the product team, but believe sure the default is now "builtin", and it's no longer "experimental". 

## Screenshots

n/a

## Browser / Platform

n/a

## Additional notes

n/a

**Comment by drothery-edb** [comment]
related to [#3429](https://github.com/EnterpriseDB/docs/issues/3439)

**Comment by drothery-edb** [comment]
@djw-m was this addressed in https://github.com/EnterpriseDB/docs/pull/3781 or is this still work to do here?

**Comment by djw-m** [comment]
Addressed in #3781
