### ISSUE TITLE
Feedback on /pgd/4/backup.mdx

### ISSUE THREAD

**Issue by rahill59** [EnterpriseDB/docs#3525]
In this section we find a note indicating:  

![Screen Shot 2023-01-11 at 10 47 06 AM](https://user-images.githubusercontent.com/73858974/211851334-53a75f00-cfc0-439c-a760-cc2fb977e78c.png)
 
Does this mean that PITR as described above is only available with Postgres Extended?  Also, would suggest we consider a more detailed set of steps of how one would accomplish taking the entire PGD back in time.  This question comes up regularly and having a more holistic explanation to direct customers to in the docs would be quite useful.

**Comment by drothery-edb** [comment]
@mwanner @PJMODOS is this note still accurate? Could someone flesh out the content with more details or an example on how this works?
