### ISSUE TITLE
Feedback on /tde/15/index.mdx

### ISSUE THREAD

**Issue by BillSmith-EDB** [EnterpriseDB/docs#3549]
On this page, there's an example command:
``initdb -D datadir -y --key-wrap-command='openssl enc -e -aes128-wrap -pbkdf2 -out `%p`' --key-unwrap-command='openssl enc -d -aes128-wrap -pbkdf2 -in `%p`'``
The backticks surrounding %p should be replaced with double-quotes

**Comment by drothery-edb** [comment]
The original Docbook source for this is: 

```
<programlisting>
initdb -D datadir -y --key-wrap-command='openssl enc -e -aes128-wrap -pbkdf2 -out %p' --key-unwrap-command='openssl enc -d -aes128-wrap -pbkdf2 -in %p'
</programlisting>
```
@BillSmith-EDB and @josh-heyer am I correct in thinking the fix is to remove the backticks as opposed to replacing them with double quotes?

**Comment by BillSmith-EDB** [comment]
I think it needs to be quoted in case the pathname has spaces in it.

Sent from my iPhone
________________________________

**Comment by drothery-edb** [comment]
Fixed with https://github.com/EnterpriseDB/docs/pull/3385/commits/ab1d5be8ddbdf9fb2d86a64cd5ad34c07d54525d
