### ISSUE TITLE
Feedback on https://www.enterprisedb.com/docs/efm/latest/

### ISSUE THREAD

**Issue by RonPrivett** [EnterpriseDB/docs#3604]
## Summary

The text here (or somewhere in the manual) should state that EFM works on both Community Edition and EPAS.

## Where would you like to see this added?

In the text at the top of this page would be great.  Or on the Platform Compatibility page (https://www.enterprisedb.com/docs/efm/latest/supported_platforms/).

## Rationale

Had this question from a customer "Does EFM support Community Edition?" --- I wanted to confirm it does via the documentation - but did not find it anywhere.

**Comment by drothery-edb** [comment]
@EFM-Bobby any concerns with adding this sentence to the landing page of the EFM doc?
