### ISSUE TITLE
HARP documentation lacks information on the health probe feature

### ISSUE THREAD

**Issue by nick-ivanov-edb** [EnterpriseDB/docs#3631]
## Summary

HARP proxy and manager have a health probe feature (since mid-2022) that is not documented in any way at all, although the corresponding parameters are shown in the sample configuration file.

## Background info

A customer has discovered the functionality by chance and is asking question about the feature use. I can explain it to the customer by looking at the product source code, but properly this should be covered in the documentation.

This feature will also be available, in a slightly different form, in the upcoming PGD Proxy, so we should also make sure it's documented there.

## Additional notes

I can create a draft for this but it has to be reviewed by product development for correctness and completeness.

**Comment by nick-ivanov-edb** [comment]
Apparently this is intentional, so I'm going to close this.

**Comment by nick-ivanov-edb** [comment]
On second thought, based on this https://edb.slack.com/archives/CSE2UK3EX/p1675982394254769?thread_ts=1675957903.685919&cid=CSE2UK3EX I think I'll re-open it.

**Comment by drothery-edb** [comment]
Per the linked Slack message, this isn't ready to be customer facing, but there is work ongoing that might result in documentation in the future.
