### ISSUE TITLE
Feedback on /biganimal/release/pricing_and_billing/index.mdx

### ISSUE THREAD

**Issue by VinnieGrack** [EnterpriseDB/docs#3682]
With recently announcement on product pricing, the EPAS pricing is now 0.2568 instead of 0.2397

**Comment by drothery-edb** [comment]
Thanks for pointing this out. The topic is updated: https://www.enterprisedb.com/docs/biganimal/latest/pricing_and_billing/#database-pricing

![image](https://user-images.githubusercontent.com/83650384/220105484-daaa6f9d-d9c2-47dd-acb8-04cc2fdc0a66.png)
