### ISSUE TITLE
Idea for https://www.enterprisedb.com/docs/pgpool/latest/

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#3731]
## Summary

From Ton Machielsen in DM (summarized):
A customer wanted to redirect write queries to a primary and load-balance read queries over the replicas. Documentation says this is the main use case for pgPool ("Transparently reroutes and ensures load balancing of read-only transactions to standby database servers"). However, internally people say pgPool doesn’t do this in a reliable way and pgPool should not be positioned for this use case. See https://edb.slack.com/archives/C018DAJ49EE/p1676546363829819 for a whole different idea of what pgPool is capable of.

@theadamwright do you think we need to adjust the documentation to align more with PgPool's strengths and weaknesses?

**Comment by theadamwright** [comment]
We carefully selected what features of Pgpool-II to support and which not to support, and we trained developers on staff to support Pgpool-II functionality. If someone runs into a reproducible case, they should share it or open a support ticket so we can fix it.  

```
Using EDB Pgpool-II adds the following benefits to your application connection infrastructure:

    Transparently reroutes and ensures load balancing of read-only transactions to standby database servers
    Reuses connections to prevent reconnects
    Brings down Postgres connections by queuing stale connections
    Integrates with failover managers to follow the primary

EDB supports the following Pgpool-II functionality:

    Load balancing
    Connection pooling
    Replication
    High availability
    Connection limits
    Watchdog
    Limiting exceeding connections
    In-memory query cache
```
