### ISSUE TITLE
Add "Knowledge base" topic to the Big Animal docs

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#3810]
### Summary

There is a tidy pile of nice articles in the public BigAnimal knowledge base. We should have a landing page that introduces this content.

### Background info

There is a growing body of content related to Big Animal that is provider-specific and subject to change based on the whims and priorities of external providers (AWS, Okta, etc.)

When possible, we should try to work in links to this content organically, either as a "further reading" section on relevant topics or inline where directly applicable. But starting out, we can improve visibility into this content by adding a dedicated KB article at the top level, introducing the platform and hinting at (or explicitly stating) what is available there.

### Additional notes

Min complete here is a "Knowledge base" topic under /biganimal/latest that links out to the public BA KB and describes its purpose.

**Comment by drothery-edb** [comment]
Fixed by #9567
