### ISSUE TITLE
Extra tick marks and other inconsistencies in Red Hat install topics

### ISSUE THREAD

**Issue by dwicinas** [EnterpriseDB/docs#3825]
### Summary

Many of the Red Hat install topics have extra tick marks in the checked-in code, even though those tick marks don't cause any rendering issues. 

Another issue is that OCL and Migration Toolkit still use the "Address other prerequisites" approach to listing prereqs, even though we moved away from that approach for all other Red Hat installations for other products.

### Where did you see the problem?

For an example of the extra tick marks, look at [this file](https://github.com/EnterpriseDB/docs/pull/3712/files#diff-dbf3f8e023ce0bab94268005c070bbd71ea5bd03f317f592e8ad5223aa53f37c) from PR 3712, now closed.

**Comment by josh-heyer** [comment]
Bunch of stuff happening here...

First, the old prereqs stuff:

	- MTK just has that in its templates for RHEL 7 and Alma/Rocky
	- OCL is more interesting - looks like we forgot to add the new version there. So those files just aren't getting updated.

The extra backticks  came from a few places. Let's start with  https://github.com/EnterpriseDB/docs/blob/c8f3a056218bb0e58ef9a4a22f235dc6911f7bee/install_template/templates/platformBase/redhat-family.njk#L7-L11

...observe carefully the intersection of the conditional (`if includePPC ... endif`) and the code block. When includePPC is turned off, the last row of ticks will still be included. There appear to be attempts to correct for this in other templates, e.g. https://github.com/EnterpriseDB/docs/blob/c8f3a056218bb0e58ef9a4a22f235dc6911f7bee/install_template/templates/platformBase/almalinux-8-or-rocky-linux-8.njk#L5

As a general rule, I would recommend avoiding situations where blocks (in either the markdown sense or the nunjucks sense) intersect in any way; it's maddening to reason about, especially once you're more than a single level of inheritance deep. Instead, prefer blocks that contain or are contained by other blocks, e.g. a nunjucks block that contains a code block that contains a different nunjucks block. As an editor modifying leaf templates, I should be able to expect that overriding a block in one leaf template will render the same way as overriding the same block in a different leaf template.

(The root issue here is that we should probably move away from the PPC conditional, as it is pretty much exists only to enable this sort of problem by failing to describe anything about either the content it generates or the context in which it generates it.)
