### ISSUE TITLE
Improve process for updating extensions topic: https://www.enterprisedb.com/docs/pg_extensions/

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#3874]
### Summary

Current process can be improved

### Where would you like to see this added?

https://www.enterprisedb.com/docs/pg_extensions/

Source: https://docs.google.com/spreadsheets/d/1GXzzVYT6CULGgGcyp0VtBfOtbxuWxkOU2pRYW42W4pM/edit#gid=1513927689

**Comment by josh-heyer** [comment]
Proposed approach: create script *in* the spreadsheet that generates an edit against the index file. When someone updates the sheet, they click the button and submit a PR. This should minimize work for as long as this spreadsheet remains the source of truth.

**Comment by djw-m** [comment]
New automated extensions builder is now incorporated. Details in https://enterprisedb.atlassian.net/wiki/spaces/DCBC/pages/3514695702/EDBDocs+tooling
