### ISSUE TITLE
Regarding "Uninstalling PostgreSQL"

### ISSUE THREAD

**Issue by YuriiS-68** [EnterpriseDB/docs#3877]
### Summary

I have Mac Ventura 13.3
Install PostgreSQL 15.2
    After launching pgAdmin 4, the File, Object, Tools and Help buttons were missing in its top panel. After that I decided to reinstall the database. The first step for this is to remove the already installed database.
After running uninstall along the pass /Library/PostgreSQL/15/uninstallpostgresql 
    A message appeared that some data could not be deleted and in folder 15 there were two not deleted folders data and Library.
    How can I completely delete this data without harming the system?

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/2e2c619e606701218573c45d710a4edb25677064/advocacy_docs/supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx

**Comment by YuriiS-68** [comment]
I made mistake, all right

**Comment by drothery-edb** [comment]
Glad you figured it out.
