### ISSUE TITLE
Allow disabling KB link in sidebar for specific topics / sections

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#3933]
## Request

Add a new frontmatter option (inheritable) that disables the KB link shown in the left-hand sidebar below the nav section.

Enable this for BigAnimal

## Background 

BA has its own knowledge base. The link shown for other products is misleading in BA context.

**Comment by djw-m** [comment]
https://github.com/EnterpriseDB/docs/pull/4112

For testing. No directory support at present. Add hideKBLink: true where hiding needed.
