### ISSUE TITLE
License Management Guide

### ISSUE THREAD

**Issue by harryvaldez** [EnterpriseDB/docs#3946]
Where can I find the license management guide for EnterpriseDB products?  I would like to get guidance in terms of how to monitor our usage of license and check if we are compliant or not.

**Comment by drothery-edb** [comment]
Thanks fore reaching out @harryvaldez. We no longer publish the License Manager Guide. You can reach out to your account or Customer Success manager for those details. If you aren't sure who that is, you can contact Support (you can find our support center at: https://www.enterprisedb.com/services/support).
