### ISSUE TITLE
Broken PDF links in EDB Postgres for Kubernetes and TPA docs

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#3978]
We have made fixes in the docs repo for broken links in the EDB Postgres for Kubernetes and TPA docs in this [PR](https://github.com/EnterpriseDB/docs/pull/3960). We also need to fix in the links in the upstream repos.

**Comment by josh-heyer** [comment]
Kubernetes backports:

- https://github.com/EnterpriseDB/cloud-native-postgres/pull/428
- https://github.com/cloudnative-pg/cloudnative-pg/issues/1990 (needs a PR)

**Comment by djw-m** [comment]
TPA backfix
* https://github.com/EnterpriseDB/tpaexec/pull/895
* (Also #4031 to fix leaked backquotes and bad case, mea culpa)
