### ISSUE TITLE
Feedback on pge 15 - "EDB Postgres Extended Server"

### ISSUE THREAD

**Issue by MattWalliEDB** [EnterpriseDB/docs#4001]
### Summary

Summary of Extended Server should state clearly that Extended Server is fully compatible with community PostgreSQL, that any application written and tested to work with community PostgreSQL will behave the same with Extended Server, and that EDB will support and fix any functionality or behavior differences between community PostgreSQL and Extended Server.  Would also help to state clearly that the purpose of Extended Server is to include TDE and PGD capabilities on top of community PostgreSQL, while maintaining parity in other respects.  FYI @theadamwright  

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/af290bf4b92b3440796b3cb6e29871ee3455b936/product_docs/docs/pge/15/index.mdx

**Comment by drothery-edb** [comment]
@theadamwright are you comfortable with these updates? See https://github.com/EnterpriseDB/docs/pull/4004

**Comment by drothery-edb** [comment]
pinged Adam on 5/3.

**Comment by theadamwright** [comment]
Updated the language here: https://github.com/EnterpriseDB/docs/pull/4004/files/43e174e2af4cc3baf35dfeb43707b0d9dc4f9a9c
