### ISSUE TITLE
Feedback on pgd 5 - "Durability and performance options"

### ISSUE THREAD

**Issue by MattWalliEDB** [EnterpriseDB/docs#4056]
### Summary

The comparison table in durability overview section uses the term "PSR Sync" ambiguously, and never defines what that term means.  The same is true for the term "PGD Legacy Sync".  It is not clear what the difference is between "PSR Sync" and "PGD Legacy Sync", or how someone would choose one vs. the other.  After some discussion, I believe "PSR Sync" actually refers to what the PGD documentation otherwise/elsewhere refers to as "Physical Standby" nodes (which are not recommended).  This table needs clarification regarding the use of these terms, or possibly "PSR Sync" should be removed from the table altogether, if it is actually referring to Physical Standby nodes (which are not recommended).   See Slack thread here:  https://edb.slack.com/archives/C01GJ1C1BNH/p1683719126951809

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/dc2537135e1a91ea63d6d67998256bbe4e210961/product_docs/docs/pgd/5/durability/index.mdx

**Comment by mwanner** [comment]
Also note that DJ already filed a Docs PR: https://github.com/EnterpriseDB/docs/pull/4049 to adjust this.

**Comment by josh-heyer** [comment]
Also being covered in #4677

**Comment by josh-heyer** [comment]
See also: #4284
