### ISSUE TITLE
Feedback on pgd 5 - "PGD overview" - missing intro to "write leader" concept

### ISSUE THREAD

**Issue by MattWalliEDB** [EnterpriseDB/docs#4059]
### Summary

The overview does not introduce the concept of "Write Leader" as it should.  The overview states "One node in each group is the target for the main application." but it doesn't state this is called the "Write Leader" and how there is only one write leader per group, that the write leader is elected using raft, etc.  These are  fundamental terms and fundamental concepts that appears elsewhere in the docs.  It does mention shadow nodes.  Neither write leader nodes or shadow nodes are mentioned in the terminology section.

```One node in each group is the target for the main application. All other nodes are described as shadow nodes (or "read-write replica"), waiting to take over when needed. If a node loses contact, processsing switches immediately to a shadow node to continue processing. If a group fails, processing can switch to the other group. Scalability isn't the goal of this architecture.```

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/a5b879051a97cd78390ff96234a6806b1cc5930d/product_docs/docs/pgd/5/overview/index.mdx

**Comment by djw-m** [comment]
#4064 introduces changes to address this - preview on https://deploy-preview-4064--edb-docs-staging.netlify.app/docs/pgd/latest/overview/
