### ISSUE TITLE
Feedback on tde 15 - "Securing the data encryption key"

### ISSUE THREAD

**Issue by nick-ivanov-edb** [EnterpriseDB/docs#4060]
### Summary

The sample key wrapping command in the documentation (`openssl enc -e -aes128-wrap -pbkdf2 -out "%p"`) does not work. Tried with OpenSSL 1.1.1 on RedHat 8.

Firstly, there's no "aes128-wrap" cipher; there is "id-aes128-wrap", but even with it I get:

```
% echo password | /usr/bin/openssl enc -e -id-aes128-wrap -pbkdf2 -pass stdin -out /tmp/blah
Error setting cipher id-aes128-wrap
140183544387392:error:0607B0AA:digital envelope routines:EVP_CipherInit_ex:wrap mode not allowed:crypto/evp/evp_enc.c:183:
```

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/a5b879051a97cd78390ff96234a6806b1cc5930d/product_docs/docs/tde/15/key_stores.mdx

This sample is also shown on the Enabling Encryption page (https://www.enterprisedb.com/docs/tde/latest/enabling_tde/)

### Expected behavior

Should have a sample command that does not fail.

**Comment by drothery-edb** [comment]
@petere can you comment on this?

**Comment by petere** [comment]
The latest docs say to use the `-aes-128-cbc` option. `-aes128-wrap` doesn't work on many platforms, that's why we changed the recommendation.

**Comment by drothery-edb** [comment]
@petere thanks for your quick respond. I have raised https://github.com/EnterpriseDB/docs/pull/4062 to fix this in the customer-facing docs. @nick-ivanov-edb thanks for bringing the issue to our attention.
