### ISSUE TITLE
OpenShift CRC is now OpenShift Local

### ISSUE THREAD

**Issue by djw-m** [EnterpriseDB/docs#4095]
https://www.enterprisedb.com/docs/postgres_for_kubernetes/latest/quickstart/#part-1---setup-the-local-kubernetesopenshift-playground

OpenShift CRC is now. called OpenShift Local.

**Comment by djw-m** [comment]
https://edb.slack.com/archives/CU5QEU5L7/p1684325615103119

**Comment by djw-m** [comment]
See https://github.com/EnterpriseDB/cloud-native-postgres/pull/453 for PR to track.

**Comment by djw-m** [comment]
Upstream change has been merged.

**Comment by josh-heyer** [comment]
This will be in the next P4K release
