### ISSUE TITLE
Broken PDF links in EDB Postgres for Kubernetes

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#4108]
Few Broken PDF links in EDB Postgres for Kubernetes remaining. See https://github.com/EnterpriseDB/docs/actions/runs/5015625210/jobs/8991422732

```
product_docs/docs/postgres_for_kubernetes/1/
rewriting links and headings
⚠️   https://github.com/EnterpriseDB/docs/blob/refs/heads/develop/product_docs/docs/postgres_for_kubernetes/1/installation_upgrade.mdx?plain=1#L46
 cannot find slug for generation-of-installation-manifests in /postgres_for_kubernetes/1/cnp-plugin.md
⚠️   https://github.com/EnterpriseDB/docs/blob/refs/heads/develop/product_docs/docs/postgres_for_kubernetes/1/operator_capability_levels.mdx?plain=1#L484
 cannot find slug for cluster-hibernation in /postgres_for_kubernetes/1/cnp-plugin.md
⚠️   https://github.com/EnterpriseDB/docs/blob/refs/heads/develop/product_docs/docs/postgres_for_kubernetes/1/declarative_hibernation.mdx?plain=1#L20
 cannot find slug for cluster-hibernation in /postgres_for_kubernetes/1/cnp-plugin.md
```

**Comment by djw-m** [comment]
These are broken links because the content in cnp-plugin.md is not there. It appears that the version of cnp-plugin.md being substituted in by the importing process is based on a pre-August 2022 version of the page. Since then, a section on installation manifest generation, hibernation, install commands, the fio command, psql sub-command (neat), and more are all not present.

The good news is that it is only cnp-plugin.md that appears to need this fix.

**Comment by djw-m** [comment]
Filed https://github.com/EnterpriseDB/cloud-native-postgres-maintenance/issues/173 to inform maintainers.

**Comment by djw-m** [comment]
Update - changes are now being made upstream, waiting for them to land upstream now.

**Comment by djw-m** [comment]
Well, those links were fixed but...

building product_docs/docs/postgres_for_kubernetes/1/postgres_for_kubernetes_v1_documentation.pdf
rewriting links and headings
⚠️⚠️  product_docs/docs/postgres_for_kubernetes/1/before_you_start.mdx:79:1
 cannot find topic for path: /postgres_for_kubernetes/1/supported_releases.md

There is no supported_releases page in the cnp version of the docs.

⚠️⚠️  product_docs/docs/postgres_for_kubernetes/1/installation_upgrade.mdx:152:27
 cannot find topic for path: /postgres_for_kubernetes/1/release_notes.md
⚠️⚠️  product_docs/docs/postgres_for_kubernetes/1/installation_upgrade.mdx:239:5
 cannot find topic for path: /postgres_for_kubernetes/1/release_notes.md

There's no top level release notes in the cnp version of the docs. Needs to change to point at rel_notes/index

⚠️⚠️  product_docs/docs/postgres_for_kubernetes/1/interactive_demo.mdx:345:38
 cannot find topic for path: /postgres_for_kubernetes/1/cnp-plugin
⚠️⚠️  product_docs/docs/postgres_for_kubernetes/1/interactive_demo.mdx:398:5
 cannot find topic for path: /postgres_for_kubernetes/1/cnp-plugin/

cnp-plugin file has changed to kubectl-plugin
