### ISSUE TITLE
Feedback on TDE 15 - "How does TDE affect performance?" - Need to provide actual information

### ISSUE THREAD

**Issue by MattWalliEDB** [EnterpriseDB/docs#4145]
### Summary

Users researching and considering TDE need to understand that the impact of TDE on performance has been designed, implemented, and measured to be very low.  Since EDB has benchmarks showing low overhead of TDE, it seems reasonable for the documentation to say more about performance impact than the currently very terse statement "Performance is in line with the general overhead for AES."   One suggestion would be to state that benchmarking tests have showed performance impact of TDE to be in low single-digit range of X%-Y%.  FYI @theadamwright 

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/4e61bae1cf171bdfbc742847e6fb290ad580d512/product_docs/docs/tde/15/index.mdx

**Comment by drothery-edb** [comment]
@MattWalliEDB I think you meant to tag @theadamwright on this, correct? @theadamwright any thoughts on Matt's suggestion?

**Comment by drothery-edb** [comment]
@theadamwright suggests we integrate the contents of [this blog](https://www.enterprisedb.com/blog/TDE-Postgres-Advanced-Server-15-Launch). Need to decide whether we want to integrate the contents or link to the blog. The risk with linking to the blog is that the blog might be taken down at some point in the future. Adam thinks we could link for now but reassess when v16 comes out.
