### ISSUE TITLE
Regarding "Installing PostgreSQL on Windows"

### ISSUE THREAD

**Issue by BenDev1001** [EnterpriseDB/docs#4167]
### Summary

psql -U postgres  
Error occured after typing this command.

like this...

C:\Users\admin>psql -U postgres
psql: error: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
        Is the server running on that host and accepting TCP/IP connections?

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/f9a3717b816b3194c9754d0cc53409feeafde425/advocacy_docs/supported-open-source/postgresql/installer/02_installing_postgresql_with_the_graphical_installation_wizard/windows.mdx

**Comment by djw-m** [comment]
Do you have a firewall installed on your system blocking port 5432? 

We work through our installers on clean, freshly installed systems, where these installations do work. Third party security or related configuration may block network ports needed to connect to the database server. Please check, and look for any dialogs from Defender or other firewalls asking for permission.

**Comment by BenDev1001** [comment]
I had faced error message while postgreSQL 15 installation. like this...
"Problem running post-install step. Installation may not complete correctly. Failed to start the database server."
I thought that this is the main reason cannot start postgre server.

**Comment by djw-m** [comment]
The psql command doesn't start the server, it connect to an already running server. So if the installation failed, then you have no running server. Assuming that the issue that caused the failure was a transient issue, reinstall the Postgres server from the installer and if an error appears during that install, capture the error for further investifation.

**Comment by BenDev1001** [comment]
I tried to install postgre 14 and 15 several times but same errors occured while installation. maybe 95% of installation.

**Comment by djw-m** [comment]
Which errors occur during installation?

**Comment by BenDev1001** [comment]
"Problem running post-install step. Installation may not complete correctly. Failed to start the database server."

During installation, a new error message pop up and there was a text like this.

**Comment by djw-m** [comment]
Open a terminal as administrator and run

pg_ctl start -D 'c:\Program Files\PostgreSQL\15\data'

and tell us what happens. If Windows Defender pops up, tell it to allow connections.

**Comment by BenDev1001** [comment]
pg_ctl: too many command-line arguments (first is
"Files\PostgreSQL\15\data'")
Try "pg_ctl --help" for more information.

This is error message.

**Comment by djw-m** [comment]
Please type the whole command, with the quote before the c:.

**Comment by BenDev1001** [comment]
Done. really works well. thanks.. May i ask you one more.
What is difference between using cmd and powershell?

**Comment by djw-m** [comment]
Different handling of quotation marks - and powershell has much more powerful scripting available.

**Comment by djw-m** [comment]
I'll close this ticket now as you are up and running.
