### ISSUE TITLE
Regarding "Uninstalling PostgreSQL"

### ISSUE THREAD

**Issue by Agata271086** [EnterpriseDB/docs#4226]
### Where would you like to see this added?

https://github.com/EnterpriseDB/docs/blob/538491537c3462b2915df53d968eaa4804fe8f25/advocacy_docs/supported-open-source/postgresql/installer/05_uninstalling_postgresql.mdx

**Comment by drothery-edb** [comment]
@Agata271086 can provide more information about the issue with this topic?
