### ISSUE TITLE
Create templates for install topics for Transporter

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#4249]
@jperozoa is the point of contact. The supported platforms are: 

- el/amd64:7
- el/amd64:8
- debian/amd64:10
- debian/amd64:11
- ubuntu/amd64:18.04
- ubuntu/amd64:20.04
- ubuntu/amd64:22.04
- sles/amd64:12sp5
- sles/ppc64le:12sp5
- sles/amd64:15sp3
- sles/ppc64le:15sp3

**Comment by josh-heyer** [comment]
Ping @djw-m when you start on this - he's interested in the process!

**Comment by josh-heyer** [comment]
@drothery-edb to talk to @dwicinas about this

**Comment by drothery-edb** [comment]
https://github.com/EnterpriseDB/docs/pull/4379

**Comment by josh-heyer** [comment]
@djw-m to sanity check ^
