### ISSUE TITLE
Feedback on repmgr 5.3.3 - "Replication Manager (repmgr)"

### ISSUE THREAD

**Issue by goodwill** [EnterpriseDB/docs#4289]
### Summary

repmgr.org is down!

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/e252781a28a3098d6a692add31b00e2438e79782/product_docs/docs/repmgr/5.3.3/index.mdx

**Comment by drothery-edb** [comment]
@goodwill thanks for reporting the issue. The URL is now www.repmgr.org. The link on that topic will be working shortly.
