### ISSUE TITLE
Need better user experience for internal and external customers that need to go older, archived versions of the doc

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#4350]
The goal is to make the archived doc links available from EDB Docs. One possible approach is to have a "Archived versions" link at the bottom of the left nav for each product that we have archived docs for. The MVP is to have links to everything we currently in [the archive](https://github.com/EnterpriseDB/docs-archive) and going forward have adding links to in EDB Docs as part of our [archiving process](https://docs.google.com/document/d/1b5Ns62aEKzdCGqogUaLsni1op0tLcUvhto3Km0TAlZw/).

Run prototype by Audrey Irwin in Support.

**Comment by drothery-edb** [comment]
PGD 3.6 will be archived in the nov/dec timeframe. It would be nice to have a process in place by then.

**Comment by josh-heyer** [comment]
https://docs-archive.enterprisedb.com/
