### ISSUE TITLE
Document all the Open Source Project import routes.

### ISSUE THREAD

**Issue by djw-m** [EnterpriseDB/docs#4401]
Objective:

We should be documenting all the incoming open source project routes, where changes are made, how to make changes (and where to make changes) where there are multiple stake holders upstream and how to work with upstream projects to assist with corrections and changes.

This ticket is a placeholder for other project-tracking and relating issues on github.

Also in Jira: https://enterprisedb.atlassian.net/browse/DF-349

**Comment by josh-heyer** [comment]
In Jira - DF-349, DF-351
