### ISSUE TITLE
Queries regarding PGD 4 release notes doc

### ISSUE THREAD

**Issue by Jagdish-Kewat-EDB** [EnterpriseDB/docs#4425]
A couple of questions regarding the index page.

1. We have a column for TPA however the actual TPA change details are not mentioned in the respective page of PGD release notes. Instead, it's updated on the customer portal page which is outside docs I believe. So I am wondering if the TPA column should be added here or not. Maybe this can be mentioned on the compatibility matrix page. If we choose to add here then can the TPA release note entries also be added to the PGD release notes page like BDR and HARP ?

2. We have a component called bdr-utilities which is part of the PGD ecosystem, however, don't have a column for it on the index page. I can see a mention of this in release notes for 4.3.1 so wondering if we can add a column for this too.

**Comment by josh-heyer** [comment]
1. TODO: @ccestes to update the links on https://www.enterprisedb.com/docs/pgd/4/rel_notes/ to point to the appropriate page under https://www.enterprisedb.com/docs/tpa/latest/rel_notes/ where they now reference the customer portal 

2. This seems a bit too granular - do you have a specific use-case for this @Jagdish-Kewat-EDB ?

**Comment by Jagdish-Kewat-EDB** [comment]
> 1. TODO: @ccestes to update the links on https://www.enterprisedb.com/docs/pgd/4/rel_notes/ to point to the appropriate page under https://www.enterprisedb.com/docs/tpa/latest/rel_notes/ where they now reference the customer portal
> 
>     2. This seems a bit too granular - do you have a specific use-case for this @Jagdish-Kewat-EDB ?

As I mentioned, this is to be consistent with the doc links for other products like BDR and HARP. As of now, the TPA links go to the customer portal which is outside the standard docs

**Comment by drothery-edb** [comment]
@Jagdish-Kewat-EDB, Josh was talking about adding the bdr-utilities to the table as being too granular. Do you have a specific use case for that?

**Comment by Jagdish-Kewat-EDB** [comment]
> @Jagdish-Kewat-EDB, Josh was talking about adding the bdr-utilities to the table as being too granular. Do you have a specific use case for that?

Ahh. ok. The bdr-utilities is also a component like Proxy and CLI so I think we should include that too

**Comment by drothery-edb** [comment]
I think whether we include bdr-utiltiies in the table is PM's call. @kelpoole what is your opinion?

**Comment by drothery-edb** [comment]
Kelly weighed in and doesn't think we should add bdr-utilities to the release notes.

**Comment by drothery-edb** [comment]
Closing this because item number 1 has been addressed
