### ISSUE TITLE
Regarding "Postgres extensions available by deployment"

### ISSUE THREAD

**Issue by ToontjeM** [EnterpriseDB/docs#4440]
### Summary

Please add PGD5 extension support.

### Where would you like to see this added?

https://github.com/EnterpriseDB/docs/blob/ad6b03ae05e8ce1f0c1ce0c0c6af817752481b6d/advocacy_docs/pg_extensions/index.mdx

**Comment by drothery-edb** [comment]
Ticket: https://enterprisedb.atlassian.net/browse/DF-355
