### ISSUE TITLE
PGD "worker":  Concepts, overview,  terminology section should explain "workers"

### ISSUE THREAD

**Issue by MattWalliEDB** [EnterpriseDB/docs#4617]
### Summary

"Worker" is a term and concept used frequently in the docs, and is a term embedded in the names of various BDR views.  However, the concept, function, architecture of "workers" is not explained anywhere in the documentation.  What is a worker?  What do they do?  What are the types of workers?  Why do I care? etc.

### Where would you like to see this added?

https://www.enterprisedb.com/docs/pgd/latest/overview/
https://www.enterprisedb.com/docs/pgd/latest/terminology/

**Comment by MattWalliEDB** [comment]
Guessing the term "worker" is just the general postgresql sense of background worker https://www.postgresql.org/docs/15/glossary.html#GLOSSARY-BACKGROUND-WORKER?  Aren't there PGD specific worker types?  If so, would be good to explain the types, what they do, etc -  I couldn't find that.  Also the term "backend" shows up in several places which I presume is the general postgresql concept of backend process:  https://www.postgresql.org/docs/15/glossary.html#GLOSSARY-BACKEND

**Comment by djw-m** [comment]
It's doubtful that explaining anything about the use of workers in PGD would offer any valuable insight to a reader of the PGD docs. There are very few references to them; the most used seem to be around the decoding worker, and that's just the abstract idea it runs. Ditto the use of backend, which is equally rare, mostly in catalog references. It's not a need-to-know concept to deploy and use, so it's not going in the terminology.
