### ISSUE TITLE
Regarding "Uninstalling PostgreSQL"

### ISSUE THREAD

**Issue by sagacic-tim** [EnterpriseDB/docs#4622]
### Summary

There are still many files left over after the installation completes. I would be helpful if those files would be identified in the documentation and their locations so that the installation can be completely purged from the system

### Where would you like to see this added?

https://github.com/EnterpriseDB/docs/blob/ee5b8d35e9206a30914c4a9a77d9e6451be4216c/advocacy_docs/supported-open-source/postgresql/uninstalling.mdx

**Comment by djw-m** [comment]
Q: Is this about the MacOS or Windows uninstall?
