### ISSUE TITLE
Regarding "Uninstalling PostgreSQL"

### ISSUE THREAD

**Issue by kiisodj** [EnterpriseDB/docs#4719]
### Summary

The uninstaller does not open.

```open /Library/PostgreSQL/15/uninstall-postgresql.app```
```sudo open /Library/PostgreSQL/15/uninstall-postgresql.app```

Neither of these open the uninstaller GUI.

I can copy the uninistaller to my Applications folder and it opens, but it errors with this message:

"This uninstaller requires root privileges. Please become superuser before executing the uninstaller"

### Where did you see the problem?

When opening the uninstaller as per docs at https://github.com/EnterpriseDB/docs/blob/d8193fce7e7c9a21b7327672841887e461195ffb/advocacy_docs/supported-open-source/postgresql/uninstalling.mdx

### Expected behavior

Uninstaller GUI opens as per docs at https://github.com/EnterpriseDB/docs/blob/d8193fce7e7c9a21b7327672841887e461195ffb/advocacy_docs/supported-open-source/postgresql/uninstalling.mdx

### Browser / Platform

OSX

**Comment by josh-heyer** [comment]
Hi! Thanks for the report. Would you mind clarifying if you've followed the instructions exactly, that is, you've: 

> - Assumed the identity of an operating system superuser
> - Navigated into the folder where the uninstaller resides:
> - Launched the uninstaller via `open uninstall-postgresql.app`

This information will help us determine whether you've encountered a bug in the installer, or in the documentation. Thanks!

**Comment by djw-m** [comment]
It appears from testing that one of the previous versions of the 15.x installers does not complete building the uninstaller. It thus starts (watch the dock) and then exits without emitting an error when run. 

The simplest fix is to reinstall Postgres 15 using the installer package; I used the 15.4 package; and let that run to completion, then when done, run the uninstaller script as directed which will remove Postgres 15 from the system, having overwritten the old, non-uninstallable version, with an uninstallable version.
