### ISSUE TITLE
[Migration Handbook][Notable Difference] Timestamp & Interval Operation difference between Oracle and EPAS/PGSQL

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/docs#4747]
### Summary

Adding one more point about timestamp adding/subtracting difference between Oracle and EPAS/PGSQL in the Notable Difference page of EDB Migration Handbook.

### Where would you like to see this added?

https://www.enterprisedb.com/docs/migrating/oracle/oracle_epas_comparison/notable_differences/

### Rationale

Hi, Support Team,

As far as I know, timestamp-related operations in Oracle is slightly different from EPAS/PGSQL.

In Oracle, users perform date shift with number or `INTERVAL` syntax
https://www.dba-oracle.com/t_add_hours_to_oracle_date.htm
https://stackoverflow.com/questions/30164819/add-two-hours-to-timestamp
https://stackoverflow.com/questions/6142916/add-day-to-timestamp

But in EPAS/PGSQL one should perform such operation with `INTERVAL` datatype and adding/subtracting a timestamp with a number is not allowed.

Usually we find this adjustment is required in many application codes.

So I think this point is worth to be addressed in the "Notable differences" of EDB Migration Handbook.

Best Regards.

**Comment by drothery-edb** [comment]
@mlewandowski-edb

**Comment by djw-m** [comment]
As always I went to check this....

```
bdrdb=> SELECT TO_TIMESTAMP('01-jan-2011 11-09-05','DD-Mon-YYYY HH24-MI-SS') + 2
bdrdb->   FROM dual;
      ?column?
--------------------
 03-JAN-11 11:09:05
(1 row)

bdrdb=>
```

I made it more explicit too:

```
bdrdb=> SELECT TO_TIMESTAMP('01-jan-2011 11-09-05','DD-Mon-YYYY HH24-MI-SS') + TO_NUMBER('2')                                         FROM dual;
      ?column?
--------------------
 03-JAN-11 11:09:05
(1 row)

bdrdb=>
```

@CC-Hsu 
Unless a working example of the feature of adding a numeric to a timestamp can be shown, I am minded to close this ticket as the notable difference does not appear to exist.
