### ISSUE TITLE
Feedback on efm 4 - "Using Failover Manager"

### ISSUE THREAD

**Issue by tureba** [EnterpriseDB/docs#4783]
### Summary

The instructions suggest creating service files inside `/usr/lib/systemd/system`. But that is not where units created by the system administrator should be placed. Instead, they should be placed in `/etc/systemd/system`.

The instructions should be clear when saying the reader should copy the reference file from its source location `/usr/lib/systemd/system` into `/etc/systemd/system` with a new name, then edit it as necessary.

### Where did you see the problem?

https://www.enterprisedb.com/docs/efm/latest/05_using_efm/#rhelcentos-7x-or-rhelrocky-linuxalmalinux-8x

**Comment by tureba** [comment]
I wasn't planning on proposing the changes, but I ended up writing https://github.com/EnterpriseDB/docs/pull/4788 for this.

**Comment by drothery-edb** [comment]
Fixes https://github.com/EnterpriseDB/docs/issues/4783

**Comment by drothery-edb** [comment]
Thank you for addressing this, @tureba! Your changes will be in today's build.
