### ISSUE TITLE
Problem on https://www.enterprisedb.com/docs/supported-open-source/postgresql/overview/

### ISSUE THREAD

**Issue by bradnoble** [EnterpriseDB/docs#4793]
### What topic is affected?

Hi all. The "Language Pack documentation" link at the bottom of the page is broken and 404s. 

See the screenshot:
<img width="1521" alt="Screenshot 2023-09-08 at 10 29 49 AM" src="https://github.com/EnterpriseDB/docs/assets/1653320/236d8def-f3c9-4bae-a14e-abb2f089d8c2">

The link leads here:
https://www.enterprisedb.com/docs/epas/latest/language_pack/

**Comment by drothery-edb** [comment]
Hey, @bradnoble! Nice to hear from you! Hope all is well. Thanks for pointing out the broken link.
