### ISSUE TITLE
Incorrect statement about GRANT ROLE replication in -"Security and roles" section

### ISSUE THREAD

**Issue by MattWalliEDB** [EnterpriseDB/docs#4844]
### Summary

Docs statement is incorrect or unclear:

"The GRANT ROLE DDL statement doesn't participate in PGD replication. Thus, execute this on each node of a cluster."   

Maybe it’s referring to situations where the BDR extension has been dropped?  Unclear… It’s also incorrect that it appears to be telling people to use PGD in multiple databases 

"This practice allows PGD to be used in multiple databases on the same PostgreSQL instance without problem "

https://www.enterprisedb.com/docs/pgd/latest/security/#pgd-defaultpredefined-roles

Those statements are contradicted elsewhere:  https://www.enterprisedb.com/docs/pgd/latest/ddl/#role-manipulation-statements which states that GRANT ROLE statements are replicated.  Elsewhere the docs state that only a single database can be enabled for PGD as of PGD5.

### Where did you see the problem?

https://www.enterprisedb.com/docs/pgd/latest/security/#pgd-defaultpredefined-roles

**Comment by djw-m** [comment]
Now BDR-4128 - https://enterprisedb.atlassian.net/browse/BDR-4128
