### ISSUE TITLE
Adding BigAnimal on GCP management cost information

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/docs#4847]
### Summary

GCP management cost of BigAnimal is not described in the documentation, please add it.

### Where would you like to see this added?

https://www.enterprisedb.com/docs/biganimal/latest/pricing_and_billing/#management-costs

### Rationale

Recently GCP is supported by the BigAnimal platform.

But in the documentation page of BigAnimal billing information, currently there is no GCP-related information.

Hope such information can be available.

Best Regards.

**Comment by djw-m** [comment]
(Rough draft)


### Google Cloud management costs

The table shows a breakdown of management costs for Google Cloud:

| Type                       	| Details                                                                                                                                           	|
| ------------------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------- |
| Google Kubernetes Engine (GKE) | BigAnimal uses GKE to orchestrate and manage the database service Managed Kubernetes Virtual Machines provisioned on Windows and Linux.           	|
| Cloud Monitoring              	| BigAnimal feeds all [logs and metrics](https://www.enterprisedb.com/docs/biganimal/latest/using_cluster/05_monitoring_and_logging/) to Google’s Cloud Monitoring. |
| Cloud Storage         	| BigAnimal uses Google Cloud Storage to store metadata about your account.                                                                                 	|
| Cloud Key Management                  	| BigAnimal uses the key management service to securely store credentials for managing your infrastructure.                                                          	|

At list price, estimated overall monthly management costs are __$400&ndash;$600__ for a single region. Check with your Google Cloud account manager for specifics that apply to your account.

To get a better sense of your Google Cloud costs, check out the Google Cloud pricing [calculator](https://cloud.google.com/products/calculator) and reach out to [BigAnimal Support](../overview/support).

**Comment by djw-m** [comment]
Note the rough draft requires (a) estimated pricing (b) the link to logs and metrics to contain information about GCP.

**Comment by josh-heyer** [comment]
Waiting on actual data here

**Comment by djw-m** [comment]
Calling on @amrita-suresh

**Comment by djw-m** [comment]
The other entries on the page link "logs and metrics" over to https://www.enterprisedb.com/docs/biganimal/latest/using_cluster/05_monitoring_and_logging/ but there's no GCP entry there. Just Azure and AWS. I can point the link for Google to that page and let that catch up if we would like this up sooner.

**Comment by amrita-suresh** [comment]
So BigAnimal actually does not integrate with Google Cloud observability the way it does with Azure/AWS, so there is no GCP info to add to this page. However this page will change in Q4 given the monitoring enhancements we're working on.
