### ISSUE TITLE
__OUTPUT__ strips leading white space in output

### ISSUE THREAD

**Issue by djw-m** [EnterpriseDB/docs#4967]
When using __OUTPUT__ with SQL tables in the output (and likely most other text)

<img width="477" alt="Screenshot 2023-11-02 at 09 51 55" src="https://github.com/EnterpriseDB/docs/assets/126472455/6d068b0f-175c-46d4-bfb1-e98c6ab6c80b">

The leading space in the output it discarded and with tables, misaligns the headers like so:

<img width="765" alt="Screenshot 2023-11-02 at 09 52 11" src="https://github.com/EnterpriseDB/docs/assets/126472455/8830ced2-577d-414f-a412-7cc34452cded">

**Comment by josh-heyer** [comment]
Fixed in 9fbee13
