### ISSUE TITLE
Broken link (typo in url) to architecture whitepaper in "BDR-Always-ON" docs

### ISSUE THREAD

**Issue by MattWalliEDB** [EnterpriseDB/docs#4973]
### Summary

Whitepaper link is broken on this page:  https://www.enterprisedb.com/docs/tpa/latest/architecture-BDR-Always-ON/

"You can check EDB's Postgres Distributed Always On Architectures [whitepaper](https://www.enterprisedb.com/promote/bdr-always-on-architectures) for the detailed layout diagrams."

The "promote" link redirects to "https://www.enterrpisedb.com/resources/white-papers/edb-postgres-distributed-always-architectures" which has multiple typos in "enterrpisedb".  It appears the correct link should be:  https://www.enterprisedb.com/resources/white-papers/edb-postgres-distributed-always-architectures

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/tpa/23/architecture-BDR-Always-ON.mdx

**Comment by djw-m** [comment]
Ok, as these docs are TPA not PGD, will sync up with @sonotley and see what the best resolution for the TPA docs is.

**Comment by djw-m** [comment]
Ok, none of this is the resposibility of the docs team. It's down to the website team who likely own the  https://www.enterprisedb.com/promote/bdr-always-on-architectures URL. Am reporting it to them and closing this ticket.
