### ISSUE TITLE
add links to downloads / installers, where appropriate

### ISSUE THREAD

**Issue by bradnoble** [EnterpriseDB/docs#50]
From the field/product sync presentation today:

> Will a developer be able to download, say, a JDBC connector directly from edb-docs?

> IMHO i'd hope we link to the official repository. this came up before through EFM with a fix needed for a JDBC issue -- we chose (rightly) to provide a link to the yum repo where efm would have picked it up instead of copying/hosting/serving it

These requests remind me of our promise, as a part of this broader redesign, to never have dead ends.

**Comment by josh-heyer** [comment]
Done as part of the templatized installer project
