### ISSUE TITLE
Feedback on pgd 5 - "Backup and recovery" should reference postgresql.conf / postgresql.auto.conf, NOT recovery.conf

### ISSUE THREAD

**Issue by harada11111** [EnterpriseDB/docs#5035]
### What topic do you have feedback on?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/pgd/5/backup.mdx

### Your feedback

Seeing the Postgresql documents , "recovery.conf" cannot be used in PostgreSQL versions 12 and later.
It prevents the instance startup.

Is this supported for EDB ? 

Also would like you add some sample process (preparation for recovery/DR , command samples for PITR , node recovery  ,etc ) on this page.

Thanks in advance.

**Comment by josh-heyer** [comment]
Not sure what you're encountering here - recovery.conf should be usable as documented. Could you clarify?

**Comment by josh-heyer** [comment]
Ah, I see what you're talking about. Yes, we need to correct this (and should probably also add a note to the 3.7 BDR docs) - good catch, thanks!
