### ISSUE TITLE
Feedback on language_pack 2 - "EDB Postgres Language Pack"

### ISSUE THREAD

**Issue by tizytissy** [EnterpriseDB/docs#5036]
### Summary

Your language pack offers for python the version 3.7, which reaches his end-of-life more the four months ago. In the meanwhile, python releases 5 main versions, the latest being 3.12. 
The same applies for perl (which is stuck to version 5.26, "dead" more than three years ago).
Have you any plan to update your language pack to the newest versions?
Thank you very much in advance.

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/language_pack/2/index.mdx

**Comment by josh-heyer** [comment]
@tizytissy I suspect our documentation is out of date on this matter - we'll look into it and update you (and the docs) as appropriate. Thanks for the report!

**Comment by djw-m** [comment]
Addressed in an updated to the language pack documentation for version 4.
