### ISSUE TITLE
PGD5 "Exploring failover" quickstart incorrectly uses local routing configuration

### ISSUE THREAD

**Issue by MattWalliEDB** [EnterpriseDB/docs#5041]
### Summary

The "exploring failover" quickstart uses a local routing configuration that doesn't match all the deployment quickstarts which use global routing 

All the deployment quickstarts use `--pgd-proxy-routing global` but "exploring failover" is written for a cluster deployed with local routing, as shown in the failover quickstart:  https://www.enterprisedb.com/docs/pgd/latest/quickstart/further_explore_failover/#displaying-the-write-leader

```
pgd show-groups
(Group        Group ID   Type   Parent Group Location Raft Routing Write Leader
-----        --------   ----   ------------ -------- ---- ------- ------------
democluster  1935823863 global                       true false
dc1_subgroup 1302278103 data   democluster  dc1      true true    kaboom
```

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/pgd/5/quickstart/further_explore_failover.mdx

### Expected behavior

The exploring failover quickstart should use commands that match the global routing configurations used in the deployment quickstarts.

**Comment by MattWalliEDB** [comment]
Thank you @lizziemacneilledb

**Comment by djw-m** [comment]
https://github.com/EnterpriseDB/docs/pull/5046 should resolve this
