### ISSUE TITLE
Regarding "Contributing Feedback and More"

### ISSUE THREAD

**Issue by erswapnil** [EnterpriseDB/docs#5070]
### Summary

I tried to examine the latest release notes on this page: https://www.enterprisedb.com/docs/pge/15/release_notes/

I cannot find the 15.5, but it is the currently available version in branch 15.

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/advocacy_docs/community/contributing/index.mdx

### Expected behavior

A release note should be available for v15.5, as its currently available version in branch

### Screenshots

<img width="1605" alt="image" src="https://github.com/EnterpriseDB/docs/assets/79270992/6fa98d09-1b2f-4411-9391-0bfb1d165154">

**Comment by josh-heyer** [comment]
These notes are now published!
