### ISSUE TITLE
Feedback on pem 9 - "Preparing the PEM database server"

### ISSUE THREAD

**Issue by amacvar** [EnterpriseDB/docs#5183]
### What topic do you have feedback on?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/pem/9/considerations/pem_pgbouncer/preparing_the_pem_database_server.mdx

### Your feedback

It would avoid annoyance to click on copy and only capture the SQL without the prompts and outputs

E.g.
> pem=# CREATE USER pem_admin1 PASSWORD 'ANY_PASSWORD' LOGIN CREATEROLE;
> CREATE ROLE
pem=# GRANT pem_admin, pem_agent_pool TO pem_admin1;
GRANT ROLE

Paste error:
> pem=# pem=# CREATE USER pem_admin1 PASSWORD 'ANY_PASSWORD' LOGIN CREATEROLE;
> ERROR:  syntax error at or near "pem"
LINE 1: pem=# CREATE USER pem_admin1 PASSWORD 'ANY_PASSWORD' LOGIN C...
        ^
pem=# CREATE ROLE
pem-# pem=# GRANT pem_admin, pem_agent_pool TO pem_admin1;
ERROR:  syntax error at or near "=#"
LINE 2: pem=# GRANT pem_admin, pem_agent_pool TO pem_admin1;
           ^
pem=# GRANT ROLE
pem-#

**Comment by jpe442** [comment]
Fix PR: https://github.com/EnterpriseDB/docs/pull/5190
