### ISSUE TITLE
"Configuring PG Failover Slots" page misses some prerequisite GUC settings

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/docs#5277]
### Summary

Hi, Team,

The official documentation page of `pg_failover_slots` misses the prerequisite settings mentioned in the extention Github page.
https://github.com/EnterpriseDB/pg_failover_slots?tab=readme-ov-file#prerequisite-settings

Specifically, `hot_standby_feedback` and `primary_slot_name` must be set in order to use `pg_failover_slots`.

Please help adding these information to the documentation.

Thanks.

### Where would you like to see this added?

https://github.com/EnterpriseDB/docs/blob/main/advocacy_docs/pg_extensions/pg_failover_slots/configuring.mdx

**Comment by nidhibhammar** [comment]
Changes are done. It will be live with the next production build.
