### ISSUE TITLE
Feedback on postgres_for_kubernetes 1 - "Transparent Data Encryption (TDE)"

### ISSUE THREAD

**Issue by michaelwilleredb** [EnterpriseDB/docs#5320]
### Summary

[cluster-example-tde.yaml](https://www.enterprisedb.com/docs/postgres_for_kubernetes/latest/samples/cluster-example-tde.yaml)
does not exist.

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/postgres_for_kubernetes/1/tde.mdx

**Comment by josh-heyer** [comment]
Fixed a while back
