### ISSUE TITLE
Feedback on pem 9 - "Installing Postgres Enterprise Manager agent on Windows"

### ISSUE THREAD

**Issue by sonotley** [EnterpriseDB/docs#5374]
### Summary

The numbering is broken - it keeps restarting at 1. Also, it references PEM 7 on the first code block, which is out of support.

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/pem/9/installing_pem_agent/windows_agent.mdx

**Comment by gvasquezvargas** [comment]
Merged and published, closing this one.
