### ISSUE TITLE
Issue while accessing the yaml (https://www.enterprisedb.com/docs/postgres_for_kubernetes/latest/samples/cluster-example-tde.yaml)

### ISSUE THREAD

**Issue by erswapnil** [EnterpriseDB/docs#5385]
### Summary

While accessing one of the sample yaml ([cluster-example-tde.yaml](https://www.enterprisedb.com/docs/postgres_for_kubernetes/latest/samples/cluster-example-tde.yaml), it shows me the error like: The requested page could not be found:

### Where did you see the problem?

in [EDB Postgres for Kubernetes](https://www.enterprisedb.com/docs/postgres_for_kubernetes/latest/) doc

### Expected behavior

it should show us the sample yaml for cluster-example-tde.yaml

**Comment by josh-heyer** [comment]
Fixed a while back
