### ISSUE TITLE
Feedback on postgres_distributed_for_kubernetes 1 - "EDB Postgres Distributed for Kubernetes"

### ISSUE THREAD

**Issue by rahill59** [EnterpriseDB/docs#5595]
### Summary

These two links from the EDB PGD for K8s documentation are not working on this page:

[Choosing your architecture](https://www.enterprisedb.com/docs/pgd/latest/architectures/)
[Choosing a Postgres distribution](https://www.enterprisedb.com/docs/pgd/latest/choosing_server/)

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/postgres_distributed_for_kubernetes/1/index.mdx

### Expected behavior

Links should revert to appropriate info.
![Screen Shot 2024-05-09 at 10 06 25 AM](https://github.com/EnterpriseDB/docs/assets/73858974/26aa8627-efc4-4856-ba43-2759fa69accd)

### Screenshots
![Screen Shot 2024-05-09 at 10 12 16 AM](https://github.com/EnterpriseDB/docs/assets/73858974/8c0ec535-1f40-40bb-a870-6012ac0ca9c7)
![Screen Shot 2024-05-09 at 10 13 27 AM](https://github.com/EnterpriseDB/docs/assets/73858974/f8033040-de54-4cbe-8ea9-c4a9d65a8962)

### Browser / Platform

Google Chrome

**Comment by josh-heyer** [comment]
Fixed in dc82817207f535384638d23852d84e9ebf257ffd
