### ISSUE TITLE
Feedback on postgres_distributed_for_kubernetes 1 - "API Reference"

### ISSUE THREAD

**Issue by michaelwilleredb** [EnterpriseDB/docs#5622]
### Summary

The API documentation doesn't wrap lines correctly. so, some of the text isn't visible - unless you lower zoon to 70% or less.

### Where did you see the problem?

https://www.enterprisedb.com/docs/postgres_distributed_for_kubernetes/latest/pg4k-pgd.v1beta1/#pgd-k8s-enterprisedb-io-v1beta1-PGDGroupSpec

### Expected behavior

wrapped text

### Screenshots

<img width="805" alt="Screenshot 2024-05-16 at 09 26 05" src="https://github.com/EnterpriseDB/docs/assets/70392367/ab27f583-1bfb-4d99-89b4-28a5700b6f26">

### Browser / Platform

Chrome Mac OS

**Comment by gvasquezvargas** [comment]
Hi, we had to close this issue. For more details on our attempts to fix it, see https://enterprisedb.atlassian.net/browse/DOCS-660.
