### ISSUE TITLE
Feedback on pgd 3.7 - "Conflicts"

### ISSUE THREAD

**Issue by ejones-edb** [EnterpriseDB/docs#5671]
### Summary

This problem exist in the docs for each of BDR/PGD 3.7, 4, and 5.  This description of the the `delete_recently_updated` conflicts default resolution is incorrect as of BDR 3.7:

```
Another type of conflicting DELETE and UPDATE is a DELETE operation that comes after the row was UPDATEd locally. In this situation, the outcome depends upon the type of conflict detection used. When using the default, [Origin Conflict Detection], no conflict is detected at all, leading to the DELETE being applied and the row removed. If you enable [Row Version Conflict Detection], a delete_recently_updated conflict is generated. The default resolution for this conflict type is to to apply the DELETE and remove the row, but this can be configured or handled via a conflict trigger.
```

That was true in 3.6 but the default resolver for that conflict was changed to `skip` in 3.7 (which is correctly listed later in the same page).

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/pgd/3.7/bdr/conflicts.mdx

### Expected behavior

This paragraph should correctly note that the default resolver for the `delete_recently_updated` conflict is `skip` in all 3.7+ BDR/PGD docs.

**Comment by josh-heyer** [comment]
Fixed by https://github.com/EnterpriseDB/docs/pull/5711
