### ISSUE TITLE
Regarding "Creating a cluster"

### ISSUE THREAD

**Issue by nick-ivanov-edb** [EnterpriseDB/docs#6144]
### Summary

On this page: [Adding a TDE key at project level](https://www.enterprisedb.com/docs/edb-postgres-ai/cloud-service/administering_cluster/projects/#adding-a-tde-key)

the link to the "adding a TDE key" page is broken: [Adding a TDE key at project level](https://www.enterprisedb.com/docs/edb-postgres-ai/cloud-service/administering_cluster/projects/#adding-a-tde-key) and the corresponding section seems to be missing on the page 

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/advocacy_docs/edb-postgres-ai/cloud-service/getting_started/creating_cluster/creating_a_cluster.mdx

### Expected behavior

Link is not broken, leads to appropriate information

**Comment by gvasquezvargas** [comment]
Solved by https://github.com/EnterpriseDB/docs/pull/6158/files and going live in the next couple of days, hence closing this one.
