### ISSUE TITLE
page <title>s are missing key metadata

### ISSUE THREAD

**Issue by bradnoble** [EnterpriseDB/docs#777]
Today the Ark page just says <title>Ark</title> but should say <title>EDB Docs - Ark</title>, or similar.

**Comment by bradnoble** [comment]
There may be complexity here when we get to versions.

**Comment by epbarger** [comment]
Easy to add "EDB Docs -" as a prefix for all titles. I can also add the version on the end if it's a doc?

**Comment by bradnoble** [comment]
Almost but not quite. We lose the product context at deeper levels. 
<img width="368" alt="Screen Shot 2021-01-28 at 4 27 00 PM" src="https://user-images.githubusercontent.com/1653320/106200964-c5ae2100-6185-11eb-9188-ef66addae40c.png">

**Comment by epbarger** [comment]
Fair enough. Adding different levels is going to take more thought, but I'll remove the versions being tacked on blindly

**Comment by cero-miedo** [comment]
Closed by #780
