### ISSUE TITLE
Add last updated data & link to revision history to advocacy topics

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#78]
Motivation:
- Provide visible indication of "freshness" & activity
- Indicate that these are living documents
- Provide credit to contributions

Not sure off-hand how this would be accomplished, but worth poking at - should be *some* metadata accessible during a build.

**Comment by bradnoble** [comment]
@cero-miedo how should we present this info on the page(s)?

**Comment by bradnoble** [comment]
Maybe the way to do this for MVP is to just show the last updated date, and link that to the file in the repo.

**Comment by epbarger** [comment]
IMO this breaks down to two separate items

1. I'll pull in the file's last updated date, and make that available to each page. I think this will be straightforward to add.

2. I'll try to create a component that can pull the page's author and other metadata from github. This will run client side so it won't be a part of the build process. Then we could just add this component to the template for all advocacy pages for example.
