### ISSUE TITLE
Some generic links that still point to /edb-docs but shouldn't

### ISSUE THREAD

**Issue by bradnoble** [EnterpriseDB/docs#801]
See the first link on this page, which takes the user to the EFM docs on Docs 1.0:
https://www.enterprisedb.com/docs/efm/latest/efm_quick_start/

The link isn't tied to an older version, so there's no reason to send the user to Docs 1.0.

Maybe we can catch and rewrite outbound links that include `/edb-docs` in the URL but don't include a version.

**Comment by josh-heyer** [comment]
In the latest-version docs, it looks like we have 700-some links to specific pages, 800-some links to the root. The former I should be able to automate rewriting, the latter I'll need to handle manually to some extent as the actual reference tends to be somewhere in the text preceding the link.

**Comment by josh-heyer** [comment]
geez, I'm getting wiggy I guess - was counting matches in the stubs & redirects files! This is much less of an issue *for now* - only 184 results in current-version docs. 50 deep links.
