### ISSUE TITLE
https://www.enterprisedb.com/docs/efm/latest/

### ISSUE THREAD

**Issue by marclinster** [EnterpriseDB/docs#843]
## Summary
The version drop down is not working (that appears to be the problem throughout the site)
This was observed on MacOS 10.5.7 with Safari 14.0.2

**Comment by bradnoble** [comment]
Recreated on Safari.

**Comment by bradnoble** [comment]
hey @marclinster, this is updated to work on Safari. Please verify when you have a minute, and close if you agree.

**Comment by marclinster** [comment]
Works now
