### ISSUE TITLE
https://www.enterprisedb.com/docs/?

### ISSUE THREAD

**Issue by marclinster** [EnterpriseDB/docs#844]
## Summary
Search does not appear to be working on any of the pages. The page appears to reformat, but no serach results are displayed.
This happens on MacOS 10.15.7 with Safari  14.0.2

**Comment by bradnoble** [comment]
Recreated on Safari.

**Comment by bradnoble** [comment]
hey @marclinster, this is updated to work on Safari. Please verify when you have a minute, and close if you agree.

**Comment by epbarger** [comment]
Closing this since the other issue was resolved, and these ended up being the same root problem
