### ISSUE TITLE
Display output of commands

### ISSUE THREAD

**Issue by epbarger** [EnterpriseDB/docs#87]
We should have a way to display the expected output of running a give block of code. This could be presented in two ways
1. As a separate block of output text, either a style-modified `CodeBlock` or a new `Output` component.
2. As a tab on a `CodeBlock`. Output text would be specified within the markdown triple backticks with a magic string IE 
```
code here
[OUTPUT]
output goes here
```

**Comment by cero-miedo** [comment]
Functionality exists, thanks for adding :)
