### ISSUE TITLE
Need ability to pull in external sources for specific pages

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#91]
## Summary
Need a walk-through for using the reference architectures at: https://github.com/EnterpriseDB/edb-ref-archs

Should live at: /building/architecture-designs/ ...

## Background info

We have a set of reference architectures being built, each with self-contained content explaining the design and eventually including scripts, etc. We need the capability to pull that content into docs, provide additional metadata and context (links to related, introduction perhaps, etc.)

Most importantly, we need the ability to organize this along with our other Journey docs - including stuff from the Containers team that will almost certainly follow this same pattern.

### Mockup

```mdx
---
title: Single-node Postgres Reference Architecture
navTitle: Single-node Architecture 
description: This architecture provides a simple single node database server that's easy to provision and maintain.
tags: list of relevant keywords (used for related articles) Ex.
    - postgresql
    - "reference-architecture"
---

<GithubContent src="https://github.com/EnterpriseDB/edb-ref-archs/blob/main/single-node/README.md" />

### See also:

- some other relevant info

```

## Additional notes

Consider a component that can reference a github path and pull content into an MDX file as needed.

**Comment by bradnoble** [comment]
This will also be required to ingest 2ndQuadrant product docs from Gitlab. Repo URLs are pending from Simon.
