### ISSUE TITLE
404 error encountered after removing duplicate content from toc of Advanced Server guide

### ISSUE THREAD

**Issue by sheet20** [EnterpriseDB/docs#918]
404 error encountered after removing duplicate content from toc # @
<img width="1250" alt="Screenshot 2021-02-10 at 11 19 43 AM" src="https://user-images.githubusercontent.com/70593977/107470912-2ed46200-6b92-11eb-9963-5bd008526758.png">

Pls take a look at the toc of both SPL and Advanced server guide to fix 404 error

**Comment by cero-miedo** [comment]
Circling in @epbarger:

It looks like this might be cache related. Files no longer exist on develop, per an update to remove duplicated content, however it looks like the link is still there on staging.

**Comment by epbarger** [comment]
Looking into this! It's interesting that the search index still has entries for those pages... makes me think the caching issue exists on the gatsby cache level, as opposed to anything going on with netlify/cloudfront caching

**Comment by epbarger** [comment]
Likely fixed by https://github.com/EnterpriseDB/docs/pull/921. Closing, if anything similar that seems caching related comes up, please ping me!

**Comment by sheet20** [comment]
Sure...Thanks a lot!
