### ISSUE TITLE
Advanced search facets presenting incorrect counts

### ISSUE THREAD

**Issue by bradnoble** [EnterpriseDB/docs#988]
See image, where the "All" facet is showing a 1 count, but there are clearly more results.

<img width="1296" alt="Screen Shot 2021-02-24 at 3 33 42 PM" src="https://user-images.githubusercontent.com/1653320/109062434-ee0e3a00-76b5-11eb-9379-ee4510d6ed9e.png">

**Comment by epbarger** [comment]
This is happening because the cloud native operator docs don't have a product assigned... I can fix that. This is more of a problem now that we've removed the top level "Doc Type" filter

**Comment by epbarger** [comment]
After PR

![Screen Shot 2021-02-24 at 5 00 37 PM](https://user-images.githubusercontent.com/2780987/109071587-e81e5600-76c1-11eb-84d2-b09d3efbe7c8.png)
