### ISSUE TITLE
SVG error messages in console

### ISSUE THREAD

**Issue by epbarger** [EnterpriseDB/docs#995]
In chrome, I'm getting a lot of `Error: <svg> attribute height: Expected length, "auto".` messages in the console

**Comment by epbarger** [comment]
rendered svg

```
<svg class="fill-orange position-relative top-minus-2 undefined" width="16" height="auto" viewBox="0 0 50 50" fill="#000000"><title>pdf</title><path></path></svg>
```

Not sure where "auto" is coming from - it's not in the source SVG files. Tried to override it within `gatsby-plugin-react-svg` with

```
    {
      resolve: 'gatsby-plugin-react-svg',
      options: {
        rule: {
          include: /static/,
          options: {
            props: { height: '16' },
          },
        },
      },
    },
```

but no luck.

**Comment by cero-miedo** [comment]
I can't replicate this, even with verbose console logging enabled. If this issue is still happening, feel free to reopen.
